### ISSUE TITLE
CartesianChart: zoom out axis scale not displayed correctly

### ISSUE THREAD

**Issue by lepton-phlb** [beto-rodriguez/LiveCharts2#556] opened 2022-07-22 09:35 UTC
**Describe the bug**
I have an issue with CartesianChart and zoom. Zoom works but after a zoom out, axis scale not displayed correctly. 

**To Reproduce**
1. zoom in on cartesian chart
2. zoom out, axes scale not displayed correctly

**Expected behavior**
Restores axes scale with same aspect at the beginning.

**Screenshots**
<img width="1807" alt="livecharts-2-zoom-issue" src="https://user-images.githubusercontent.com/9680637/180410131-95a44c9c-4dca-4da0-9d93-2bc76492786b.png">

**Desktop PC**
 - Device: Desktop PC
 - OS: windows 10
 

**Additional context**
Visual studio 2022, winform application project, .NET framework 4.6.2, live charts 2.0.0-beta.300

**Comment by beto-rodriguez** [comment] 2022-08-20 01:26
It seems that this issue should be fixed with 259569a2fc54505b2eadeef2beddb74a185da64c and is related to #555.

Please let me know if this works for you in version beta.360 or later (not published on NuGet yet, but it will be soon)

**Comment by beto-rodriguez** [comment] 2022-09-01 18:29
I am unable to reproduce this issue, I will close this for now, let me know if the issue persists in the latest version of the library.

**Closed by beto-rodriguez** 2022-09-01 18:29 UTC
Labels: bug, waiting for reply
