### ISSUE TITLE
Chart does not refresh, just after display changes (window size, dragging screen between displays...)

### ISSUE THREAD

**Issue by NorbiHub** [beto-rodriguez/LiveCharts2#756] opened 2022-11-16 13:35 UTC
There is a fully working application which does not work on some hosts, because the linecharts does not appear just after some cases:
- when we use multiple diplays and we drag the application from a display to another
- when we use multiple displays and we unplug the one on which the application is shown
- if we lock the PC and then sign in again
- if we make the screen full size

These are the cases that we have already experienced, but there can be more.
On the picture you can see that the tooltip is shown if I point on a chartpoint, but the chart is not.

![MES_displayProblem](https://user-images.githubusercontent.com/65021582/202179896-6d30274a-d362-445f-9d1f-7fa62af3ba73.png)
Do you have any idea why is it happening? Can I do some display setting to eliminate this, or is it a code-related issue?
Thank you!

**Comment by beto-rodriguez** [comment] 2022-11-24 19:38
Probably an external bug, please check if any of this work:

https://github.com/dotnet/wpf/issues/3817
https://github.com/beto-rodriguez/LiveCharts2/issues/453
https://github.com/beto-rodriguez/LiveCharts2/issues/509

**Comment by beto-rodriguez** [comment] 2023-03-02 23:03
I am closing this since I am not able to reproduce the issue, feel free to reply if you find any evidence that the issue belongs to LiveCharts, please notice the possible external fixes in the previous comment above.

**Closed by beto-rodriguez** 2023-03-02 23:03 UTC
Labels: not verified
