### ISSUE TITLE
ChartPointPointerHover Events are not raised when TooltipPosition is set to Hidden

### ISSUE THREAD

**Issue by fitdev** [beto-rodriguez/LiveCharts2#1437] opened 2024-02-02 13:02 UTC
**Describe the bug**
`Series<,,,>.ChartPointPointerHover` and `Series<,,,>.ChartPointPointerHoverLost` Events are not raised when Chart's `TooltipPosition` is set to `Hidden`.

**Expected behavior**
Showing or hiding of tooltips should _not_ influence whether or not pointer-related events are raised.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Avalonia 11.0.7

**Comment by beto-rodriguez** [comment] 2024-11-03 21:05
I will close this as duplicate of #1621, the good news is that this is already fixed and will be included in the next version of the library.

**Closed by beto-rodriguez** 2024-11-03 21:05 UTC
Labels: requires-attention
