### ISSUE TITLE
Chart starts in the "wrong" location until "right" location is moused over

### ISSUE THREAD

**Issue by begleysm** [beto-rodriguez/LiveCharts2#773] opened 2022-11-24 21:35 UTC
**Describe the bug**
I am using LiveCharts2 in Avalonia.  I have two charts setup inside a Grid.  When I open the window the charts are displayed "offset" up and to the left.  Once I mouse-over the correct location they "pop" into position.

**Expected behavior**
I would expect the charts to show up in their designated grid spot upon the window opening.

**Screenshots**
Here is a GIF showing what I mean.
![must-mouse-over](https://user-images.githubusercontent.com/1275999/203865232-c453b1e9-1bd0-46a2-a2da-2957c55391bc.gif)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Framework: Avalonia
 - Version: Avalonia 0.10.18, LiveCharts2 2.0.0-beta.330

**Code**
VIEW
```xml
<Grid RowDefinitions="60,160,60,60,100,100" ColumnDefinitions="*,*,*,*">
						
	.
	.
	.

	<Grid RowDefinitions="40,*" ColumnDefinitions="*,*" Grid.Row="1" Grid.Column="0" Grid.ColumnSpan="4">
		<TextBlock Grid.Row="0" Grid.Column="0" HorizontalAlignment="Center" VerticalAlignment="Bottom">Control Network Status</TextBlock>
		<Border Grid.Row="1" Grid.Column="0" BorderBrush="Green" BorderThickness="2" CornerRadius="3">
			<lvc:CartesianChart EasingFunction="{x:Null}" Series="{Binding NetworkTrafficSeries}"></lvc:CartesianChart>
		</Border>
		<TextBlock Grid.Row="1" Grid.Column="0" VerticalAlignment="Top" FontSize="10" FontStyle="Italic" Margin="5,5,0,0">Dropped Packets:    In = 10    Out = 2</TextBlock>
		
		<TextBlock Grid.Row="0" Grid.Column="1" HorizontalAlignment="Center" VerticalAlignment="Bottom">Data Network Status</TextBlock>
		<Border Grid.Row="1" Grid.Column="1" BorderBrush="Red" BorderThickness="2" CornerRadius="3">
			<lvc:CartesianChart EasingFunction="{x:Null}" Series="{Binding NoOutputTrafficSeries}"></lvc:CartesianChart>
		</Border>
		<TextBlock Grid.Row="1" Grid.Column="1" VerticalAlignment="Top" FontSize="10" FontStyle="Italic" Margin="5,5,0,0">Dropped Packets:    In = 5    Out = 1234</TextBlock>
	</Grid>
	
	.
	.
	.
	
</Grid>
```

VIEWMODEL
```csharp
.
.
.
public class VPXModuleWindowViewModel : ViewModelBase
    {
        private static double[] DataIn = new double[100];
        private static double[] DataIn2 = new double[100];
        private static double[] DataOut = new double[100];
        private static double[] DataZero = new double[100];

        public VPXModuleWindowViewModel()
        {
            Random rnd = new Random();
            for (int i = 0; i < DataIn.Length; i++)
            {
                DataIn[i] = rnd.Next(100);
                DataIn2[i] = rnd.Next(100);
                DataOut[i] = rnd.Next(100);
                if (i < 20)
                {
                    DataZero[i] = rnd.Next(100);
                }
                else
                {
                    DataZero[i] = 0;
                }
            }
        }
        
        public ISeries[] NetworkTrafficSeries { get; set; } =
        {
            new LineSeries<double>
            {
                Name = "In",
                Values = DataIn, 
                Fill = null,
                GeometrySize = 0,
                LineSmoothness = 0,
                Stroke = new SolidColorPaint(SKColors.YellowGreen) { StrokeThickness = 1 }
            },

            new LineSeries<double>
            {
                Name = "Out",
                Values = DataOut,
                Fill = null,
                GeometrySize = 0,
                LineSmoothness = 0,
                Stroke = new SolidColorPaint(SKColors.DodgerBlue) { StrokeThickness = 1 }
            }
        };
        
        public ISeries[] NoOutputTrafficSeries { get; set; } =
        {
            new LineSeries<double>
            {
                Name = "In",
                Values = DataIn2, 
                Fill = null,
                GeometrySize = 0,
                LineSmoothness = 0,
                Stroke = new SolidColorPaint(SKColors.YellowGreen) { StrokeThickness = 1 }
            },

            new LineSeries<double>
            {
                Name = "Out",
                Values = DataZero,
                Fill = null,
                GeometrySize = 0,
                LineSmoothness = 0,
                Stroke = new SolidColorPaint(SKColors.DodgerBlue) { StrokeThickness = 1 }
            }
        };
    }

.
.
.
```

**Comment by beto-rodriguez** [comment] 2022-12-18 19:59
Hello and thanks for the issue.

This is strange, I am not completely sure if this is an issue of Live Charts, notice in this repository all the charts start or their actual position, could you please provide a small repository with the issue?

**Comment by begleysm** [comment] 2023-01-06 19:54
I probably can't create a minimal example at this time.  I changed the way my GUI works and it doesn't happen anymore, but it was long ago enough that I'm not quite sure how to quickly get back there.  You can probably close this.

**Comment by GF-Huang** [comment] 2023-02-13 22:55
I have similar problem. After add data into series, the chart not show correct until I click/zooming it.

![BQuOoEYFLZ](https://user-images.githubusercontent.com/4510984/218592958-f89f3d9d-c0a6-4e71-b8ac-36865ad221cf.gif)

**Comment by beto-rodriguez** [comment] 2023-06-06 01:31
This is hard to reproduce, in general there will be multiple improvements in the library in the next version (beta-800), I will close this for now since we can not reproduce it and it is probably already fixed, I  fixed a bunch of render issues and added multiple tests, probably this got fixed some there in https://github.com/beto-rodriguez/LiveCharts2/pull/1028 or https://github.com/beto-rodriguez/LiveCharts2/pull/1021 please open a new issue if the error persists after beta 800 version.

**Closed by beto-rodriguez** 2023-06-06 01:31 UTC
Labels: more info required, avalonia, not verified
