### ISSUE TITLE
Axis Ticks vanish after initial Chart display animation

### ISSUE THREAD

**Issue by VincentH-Net** [beto-rodriguez/LiveCharts2#1344] opened 2023-11-06 14:38 UTC
When a (`CartesianChart`) with axis ticks is displayed, the ticks are visible until the initial display animation of the Chart completes.
Then the ticks disappear. Happens on Windows and Android - did not check other platforms.

**To Reproduce**
1. Add `TicksPaint = new SolidColorPaint(new SKColor(0,0,0,0))` to any `Axis` on a `CartesianChart` (does not matter whether `XAxes` or `YAxes`)
2. Display the Chart
3. See the error after the Chart display animation ends

**Expected behavior**
Ticks remain visible

**Video**
![LiveChartsTicksDisappear](https://github.com/beto-rodriguez/LiveCharts2/assets/1872271/3417386c-8bcf-4a06-b150-304be6f2d767)

**Desktop:**
 - OS: Windows 11 Pro
 - Windows App SDK 1.4 app
 - LiveChartsCore.SkiaSharpView.WinUI 2.0.0-rc1.2
 
**Smartphone:**
 - Device: Android emulator Pixel 5
 - OS: Android 13
 - Uno Platform 4.10 app
 - LiveChartsCore.SkiaSharpView.Uno.WinUI 2.0.0-rc1.2

**Comment by beto-rodriguez** [comment] 2023-11-10 18:17
Hi and thanks for the report.

I fixed a lot of axes related issued in the last days, currently on the dev branch I am not able to reproduce this issue, I think that this issue will be gone in `rc2` version.

**Comment by beto-rodriguez** [comment] 2024-10-22 15:06
This is fixed with [0b605b4](https://github.com/beto-rodriguez/LiveCharts2/pull/1656/commits/0b605b4724a694fc8bccef49cdd430ad97bc3244).

**Closed** 2024-10-24 20:37 UTC
Labels: visual glitch
