### ISSUE TITLE
Label and ToolTip color don't change after changing the series color - Pie and Bar chart (.MAUI)

### ISSUE THREAD

**Issue by Visutronik** [beto-rodriguez/LiveCharts2#1375] opened 2023-11-23 11:29 UTC
**Describe the bug**
I use a database. In my database exist articles with a color value. I have a SQL request for the charts.
I create the series at runtime depends on the SQL result.

**To Reproduce**
I use this example [https://livecharts.dev/docs/Maui/2.0.0-beta.950/samples.general.mapPoints](https://livecharts.dev/docs/Maui/2.0.0-beta.950/samples.general.mapPoints)

**Screenshots**
Pie:
![image](https://github.com/beto-rodriguez/LiveCharts2/assets/67111377/4ceeabe2-843c-462d-8d6d-f6cb1009a95f)

Bar:
![image](https://github.com/beto-rodriguez/LiveCharts2/assets/67111377/6a775faf-2b41-4ba8-b270-f188e8c518bd)

**Desktop (please complete the following information):**
 - OS: Windows 10 (.MAUI 7)
 - Version beta-950

**Smartphone (please complete the following information):**
 - no

**Additional context**
Code to create the chart series:
![image](https://github.com/beto-rodriguez/LiveCharts2/assets/67111377/d929f57a-15c9-4d98-9db1-fe608ea54223)

![image](https://github.com/beto-rodriguez/LiveCharts2/assets/67111377/21c77218-0c4e-427a-99b8-79e1fdfb5c81)

The code for the Bar is similar to the code for the Pie but has more Variables.

**Comment by Visutronik** [comment] 2023-11-23 11:30
Edit: The colors of the elements of the Bar and Pie charts are correct but not of the Legend and the ToolTip

**Comment by network-interface-controller** [comment] 2023-11-29 16:41
Seems to be a duplicate of https://github.com/beto-rodriguez/LiveCharts2/issues/1335

**Closed** 2024-10-21 20:22 UTC
Labels: priority 1, requires-attention
