### ISSUE TITLE
System.MissingMethodException:“找不到方法:“Void LiveChartsCore.SkiaSharpView.PieSeries`1..ctor()”。”

### ISSUE THREAD

**Issue by Ydmplee** [beto-rodriguez/LiveCharts2#1327] opened 2023-10-22 14:23 UTC
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by beto-rodriguez** [comment] 2023-10-27 19:24
Hi

I will close this for now since it seems that the issue report is not complete.

Please feel free to reply with more details on how to reproduce the issue, or just create a new issue if it persists.

**Closed by beto-rodriguez** 2023-10-27 19:24 UTC
