### ISSUE TITLE
Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by sigmarsson** [beto-rodriguez/LiveCharts2#935] opened 2023-02-15 14:33 UTC
**Describe the bug**
Several charts employed on a ```Pivot``` control and by changing among the pivots several times, this exception was thrown. 

**To Reproduce**
```
    <Pivot>
        <Pivot.RightHeader>

        </Pivot.RightHeader>

        <PivotItem Header="Atmosphere">
            <view:chart/>
        </PivotItem>

        <PivotItem Header="Air Quality Index">
            <view:chart/>
        </PivotItem>

        <PivotItem Header="Total Precipitation">
            <view:chart/>
        </PivotItem>

        <PivotItem Header="Solar Radiation">
            <view:chart/>
        </PivotItem>

    </Pivot>

```
**Screenshots**
![image](https://user-images.githubusercontent.com/43340959/219054871-cd60d5f6-bffd-4947-903e-58bc7b8a52db.png)

**Desktop (please complete the following information):**
 - OS: Microsoft Windows [Version 10.0.22621.1265]

**Additional context**
v 701.

**Comment by sigmarsson** [comment] 2023-02-25 14:35
The same occured again :


```
   at LiveChartsCore.Axis`3.InvalidateCrosshair(Chart`1 chart, LvcPoint pointerPosition)
   at LiveChartsCore.CartesianChart`1.InvokePointerMove(LvcPoint point)
   at LiveChartsCore.SkiaSharpView.WinUI.CartesianChart.OnPointerMoved(Object sender, PointerRoutedEventArgs e)
   at WinRT._EventSource_global__Microsoft_UI_Xaml_Input_PointerEventHandler.EventState.<GetEventInvoke>b__1_0(Object sender, PointerRoutedEventArgs e)
   at ABI.Microsoft.UI.Xaml.Input.PointerEventHandler.Do_Abi_Invoke(IntPtr thisPtr, IntPtr sender, IntPtr e)
```

**Comment by sigmarsson** [comment] 2023-10-01 12:04
![image](https://github.com/beto-rodriguez/LiveCharts2/assets/43340959/8d7deca8-c49b-4ec9-8025-4d9272fe411d)

Will/can you fix it for 2.0 ?

**Comment by beto-rodriguez** [comment] 2023-11-10 15:37
I am not completely sure if I got this fixed with a previous commit, but I am not able to reproduce this in the dev branch.

`rc2` will be published soon luckily the issue will be gone there.

![pivot](https://github.com/beto-rodriguez/LiveCharts2/assets/10853349/466fc337-bfb2-4207-a18c-2099983fbe38)

**Comment by beto-rodriguez** [comment] 2023-11-11 21:11
I will close this for now since it seems fixed in rc2 version, feel free to reply or open a new issue if it persists.

**Comment by DamianSuess** [comment] 2023-11-23 17:22
@beto-rodriguez out of curiosity, which version of .NET MAUI was this tested against without it throwing that error?

As a publisher myself, i'm sorry to report this as I don't like seeing this kind of comment pop up after the issue closed either.

* .NET MAUI v7
* Windows 10
* LiveCharts2-rc2

![image](https://github.com/beto-rodriguez/LiveCharts2/assets/1216684/44f094a4-717b-437b-800a-ae29e845b210)

If I can this weekend, I'll try to dig in further on your latest branch

**Comment by DamianSuess** [comment] 2023-11-24 19:45
@beto-rodriguez, for the issue that I am running into, I'm not sure if it's the same as the other folks.

For mine, it was on closing the application, with the `CartesianChart` no longer receiving updates for a live update.
The app is using .NET MAUI v7.0 running in WinUI.

When attempting to reproduce with the latest `master`, the closest I can relate to is closing the app while running the "General / MultiThread2" sample. However, that is throwing a different error.  Just wanted to let you know, i'm still digging around to try & help out.

Thank you again Mr. Rodriguez! I love this user control

**Comment by beto-rodriguez** [comment] 2023-11-24 20:13
That seems like a different issue, issue raised.

@DamianSuess That issue seems to be at SkiaSharp/MAUI (not sure yet), I will try to find a workaround for it, notice it does not happen on the WinUI control, it only occurs on MAUI (in Windows).

**Closed by beto-rodriguez** 2023-11-24 20:13 UTC
Labels: requires more research, not verified

**Comment by DamianSuess** [comment] 2023-11-25 01:11
Good call on splitting this one off. I'm still digging into my scenario as well
I appreciate you taking the time to take a peek.
