### ISSUE TITLE
Its neccesary using System.Windows.Forms; for design uwp app(LiveCharts2)

### ISSUE THREAD

**Issue by HumbertoML** [beto-rodriguez/LiveCharts2#189] opened 2021-09-16 01:17 UTC
Hi, I was looking at the examples in this package and it turns out that the uwpsample project links another project (ViewModelSamples) viewmodel to the WinFormsSample.Axes.Shared project from winforms.

![image](https://user-images.githubusercontent.com/22565720/133534166-17d46604-b088-4f89-a3cc-4eeaea62128e.png)

my question is, does this create compatibility problems?
can I publish the app with windows forms uwp in the store?
is there a way to display the charts without this reference?

**Comment by beto-rodriguez** [comment] 2021-09-16 17:36
@HumbertoML this is by design, you should not face any issue.

> is there a way to display the charts without this reference?

*Answer:* Yes, it is not required, that structure helps me to build the library faster.

This structure of the projects helps to share the code at the `ViewModelSamples` project in all the samples projects, this is a common pattern.

There are multiple places where you can learn about it, this is a good start:

https://docs.microsoft.com/en-us/archive/msdn-magazine/2009/february/patterns-wpf-apps-with-the-model-view-viewmodel-design-pattern

When the site is published, everything will be easier, but for now this structure helps me to build the library faster.

I will close this issue for now, feel free to open a new one if you require it.

**Closed by beto-rodriguez** 2021-09-16 17:36 UTC
