### ISSUE TITLE
Error MSB3030 Could not copy the file ***.xbf because it was not found.

### ISSUE THREAD

**Issue by fiftin** [beto-rodriguez/LiveCharts2#192] opened 2021-09-18 13:42 UTC
**Describe the bug**
Compilation error:
MSB3030	Could not copy the file ".nuget\packages\livechartscore.skiasharpview.winui\2.0.0-beta.71\lib\net5.0-windows10.0.19041\LiveChartsCore.SkiaSharpView.WinUI\DefaultTooltip.xbf" because it was not found.	

**To Reproduce**
1. Install LiveChartsCore.SkiaSharpView.WinUI v 2.0.0-beta.71

**Expected behavior**
Successful compilation.

**Screenshots**
![image](https://user-images.githubusercontent.com/914224/133890901-60b5f904-e0f4-4318-a834-de87549bb967.png)

**Desktop (please complete the following information):**
 - OS: Window 10
 - VS 2022 Preview

**Comment by eaglestorm** [comment] 2021-09-27 12:56
Having the same issue with VS 2022.  also using .net 6.0

**Comment by beto-rodriguez** [comment] 2021-09-27 12:58
This issue affects WinUI NuGet package.

**Comment by lesterbotello** [comment] 2023-10-02 20:00
Looks like this issue is back in `2.0.0-rc1.2`. Tested with a blank Uno Platform project.

**Comment by BigWarren** [comment] 2023-10-07 17:43
Can confirm, the issue is back on 2.0.0-rc1.2 with blank Uno project

**Comment by beto-rodriguez** [comment] 2023-11-10 14:55
This is already fixed with #1341, this will be included in the next release of the library (rc2), I will close this for now, but we can use #1329 to track this issue.

**Closed by beto-rodriguez** 2023-11-10 14:55 UTC
Labels: winui, priority 0
