### ISSUE TITLE
Setting MinLimit on Y-Axis stops autoscaling behavior of MaxLimit

### ISSUE THREAD

**Issue by jaeaton** [beto-rodriguez/LiveCharts2#374] opened 2022-01-24 22:19 UTC
**Describe the bug**
When MinLimit is set on Y-Axis, the MaxLimit is no longer automatically scaled

**To Reproduce**
Set Y-Axis min limit to 0

`YAxes = new List<Axis>
            {
                new Axis
                {
                    MinLimit = 0,
                    //MaxLimit = (DataHandlingViewModel.maxData.MaxTension.Tension)*1.1+100
                    //MaxLimit = 6000
                }
            };`

**Expected behavior**
Y-Axis should always start with 0 and the maximum value should be scaled to the data

**Screenshots**

**Desktop (please complete the following information):**
 - OS:Win 10
 - Version: Beta 100

**Additional context**
Add any other context about the problem here
Setting the MaxLimit to a value works and creates a fixed axis.
Setting MaxLimit to a variable doesn't work (although this could be me)

![Screenshot 2022-01-24 170405](https://user-images.githubusercontent.com/47159608/150872673-94147e9d-ee20-4289-8b9d-fee4fd99feb2.jpg)
![Screenshot 2022-01-24 170958](https://user-images.githubusercontent.com/47159608/150873389-493eb0af-5bde-4bdf-935c-082e5d87047c.jpg)

.

**Comment by beto-rodriguez** [comment] 2022-04-26 23:14
Hi! and thanks for the report.

 I am not able to reproduce this, am I missing something? I took the Lines/AutoUpdate sample and forced the `MinLimit` of the Y axis to 0, I keep adding points with no issues it behaves as it should.

Probably it got fixed with a previous commit?

**Comment by beto-rodriguez** [comment] 2022-04-27 13:37
This seems to be fixed in the current version, please feel free to open a new issue if it persists.

**Closed by beto-rodriguez** 2022-04-27 13:37 UTC
Labels: more info required
