### ISSUE TITLE
WPF: Updating a cartesian chart with empty data not possible

### ISSUE THREAD

**Issue by network-interface-controller** [beto-rodriguez/LiveCharts2#1365] opened 2023-11-18 13:25 UTC
**Describe the bug**
In my scenario I have a dropdown in the UI that allows a user to select different data sets which are then visualized by a cartesian chart. However, if a data set is empty and does not possess the considered information the cartesian chart is not updated with the provided empty list of series and shows simply nothing (as other chart types do) but it persists the latest data set that was selected before.

**To Reproduce**
1. Create a cartesian chart and bind the series property in your XAML view to a public property of type List<ISeries> in your view model
2. Create a series with data and add it to this list --> data is displayed correctly in UI
3. Replace the previous series in List<ISeries> by an empty one during runtime --> The previous series is still displayed although the data is obsolete

```
public List<ISeries> MySeries
{
    get
    {
        if (data == null)
            return new List<ISeries>();

        var dataSeries = new ColumnSeries<double>
        {
            Values = ...,
            Fill = ...,
            DataLabelsPaint = ...,
            DataLabelsPosition = ...,
            DataLabelsFormatter = (chartPoint) => $"...",
            XToolTipLabelFormatter = (chartPoint) => $"...",
            IsVisibleAtLegend = false
        };

        return new List<ISeries> { dataSeries };
    }
}
```

**Expected behavior**
Charts behave consistently and cartesian chart (like others) does not display anything if an empty set of data is provided

**Desktop (please complete the following information):**
OS: Windows 10, Version 22H2
Browser --> Not applicable; WPF app
Version: LiveChartsCore 2.0.0-rc2, LiveChartsCore.SkiaSharpView.WPF 2.0.0-rc2
Framework: .NET 7.0

**Smartphone (please complete the following information):**
--> NA

**Comment by beto-rodriguez** [comment] 2024-09-13 18:51
Hi

There are a few things I see here, I think that the issue is that when your property changes, you are not raising the `INotifyPropertyChanged.PropertyChanged` event, this is how MVVM works and is something that most of the time the library does for you, but in this case where you are changing the instance, you must explicitly notify the UI to update.

Another alternative is to use an `ObservableCollection<T>` instead of a `List<T>` and clear the values and add the new ones, this way the library will handle the updates for you.

I am not completely sure why it seems that it updates sometimes, that might depend on your code, maybe somewhere else the PropertyChanged event is raised (because maybe you are using LiveCharts objects).

I will close this for now, I don't think this is an issue with the library, but feel free to reply if there is something else I can help with.

**Closed by beto-rodriguez** 2024-09-13 18:51 UTC

**Comment by network-interface-controller** [comment] 2024-09-14 11:05
Hi @beto-rodriguez ,

thanks for your feedback! The INotifyPropertyChanged.PropertyChanged was handled correctly (although not part of my code snipped above). However, after some time-consuming investigations it turned out that I had simply forgotten to toggle the visibility property of the considered chart in my XAML - that's why it worked for the other charts. Often the root cause is located right in front of the monitor....

**Comment by beto-rodriguez** [comment] 2024-09-14 14:53
@network-interface-controller glad you found it!
