### ISSUE TITLE
Avalonia Can't find Package

### ISSUE THREAD

**Issue by henrydunphy** [beto-rodriguez/LiveCharts2#539] opened 2022-06-29 14:59 UTC
I am trying to implement LiveCharts2 into my project, but keep getting compile errors form the XAML file saying "Unable to resolve type PieChart from namespace using:LiveChartsCore.SkiaSharpView.Avalonia". The program will run, but it doesn't display the graphs.
I installed LiveCharts from the Package manager console using this line: "Install-Package LiveChartsCore.SkiaSharpView.Avalonia -Version 2.0.0-beta.300"

I set up my view like this:

```
<UserControl xmlns="https://github.com/avaloniaui"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
             xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
             mc:Ignorable="d"
             xmlns:lv="clr-namespace:LiveChartsCore;assembly=LiveChartsCore"
             xmlns:lvc="using:LiveChartsCore.SkiaSharpView.Avalonia"
             x:Class="PowderInventory.InventoryManagement.UI.Views.OperatorView">
	<StackPanel HorizontalAlignment="Center" VerticalAlignment="Center">
		<TextBlock Text="Hi, this is the operator view" />
		<TextBlock Text="{Binding UrlPathSegment}" />
		
		<lvc:PieChart Series="{Binding Series}" LegendPosition="Right"/>
	</StackPanel>
</UserControl>
```

and my ViewModel uses the Series data from the sample

```
public IEnumerable<ISeries> Series { get; set; } = new ISeries[]
         {
             new PieSeries<double> { Values = new double[] { 2 }, Name = "Slice 1" },
             new PieSeries<double> { Values = new double[] { 4 }, Name = "Slice 2" },
             new PieSeries<double> { Values = new double[] { 1 }, Name = "Slice 3" },
             new PieSeries<double> { Values = new double[] { 4 }, Name = "Slice 4" },
             new PieSeries<double> { Values = new double[] { 3 }, Name = "Slice 5" }
         };
```

**Comment by nothingalike** [comment] 2022-07-14 00:19
same here

**Comment by snaipasomoh** [comment] 2022-07-21 14:10
I had the same problem with CartesianChart. The problem was that I used tag <v:FooView/> in my MainWindow.axaml. After changing it to <vm:FooViewModel/> the data on graph appeared.

(XAML exception is still here, but the app compiled and works fine)

**Comment by beto-rodriguez** [comment] 2022-08-19 23:01
I am not able to reproduce this issue, it seems that the latest version in NuGet works properly.

I will close this for now, let me know if the issue persists.

**Closed by beto-rodriguez** 2022-08-19 23:01 UTC

**Comment by lonelyion** [comment] 2022-12-07 01:57
I have the same issue even with a newly created Avalonia project. Avalonia Diagnostics output:
```
09:40:27.690 [Error] 27592 UpdateXamlResult error
System.Xaml.XamlException: 'Unable to resolve type CartesianChart from namespace using:LiveChartsCore.SkiaSharpView.Avalonia Line 46, position 5.' Line number '46' and line position '5'.
```
The error only occurs in axaml designer while the app compiling and working fine.

**Comment by exe-0535** [comment] 2023-03-04 13:54
> Hi. I also was having this issue. CartesianChart was working, but it wasn't showing on designer preview. I added this to Program.cs in BuildAvaloniaApp method.
> 
> **`GC.KeepAlive(typeof(LiveChartsCore.SkiaSharpView.Avalonia.CartesianChart).Assembly);`**

This didn't fix it for me, still can't see the chart on the preview, even on the latest version of lvc avalonia @beto-rodriguez

**Comment by EricZeiberg** [comment] 2023-05-22 17:05
Having the same issue

**Comment by dnagelCS** [comment] 2024-08-16 21:24
I also got this issue. After adding @marcosnathan solution I got this unhandled exception (In a different Avalonia project, I didn't have to add the GC.KeepAlive line to get this exception):
```
System.Reflection.TargetInvocationException: 'Exception has been thrown by the target of an invocation.'

Inner Exception
TypeLoadException: Method 'add_VisualElementsPointerDown' in type 'LiveChartsCore.SkiaSharpView.Avalonia.CartesianChart' from assembly 'LiveChartsCore.SkiaSharpView.Avalonia, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc92a3e13d40c573' does not have an implementation.
```

**Comment by qingyu-sama** [comment] 2024-09-12 04:34
When I replaced
```
xmlns:lvc="using:LiveChartsCore.SkiaSharpView.Avalonia"
```
with
```
xmlns:lvc="clr-namespace:LiveChartsCore.SkiaSharpView.Avalonia;assembly=LiveChartsCore.SkiaSharpView.Avalonia"
```
the preview of axaml designer was normal
