### ISSUE TITLE
WPF charts zoom control

### ISSUE THREAD

**Issue by EdenMeshulam28** [beto-rodriguez/LiveCharts2#549] opened 2022-07-13 06:26 UTC
**Describe the bug**
In WPF when using Cartesian Chart & zoom on full screen (without and control that limits the charts width and height), zoom and pan options work well.
However when the Cartesian Chart has any limitation on its size for some reason the is no reaction to zoom and pan actions (with no other changes in the charts settings).

**To Reproduce**
just by using a Cartesian Chart  in a grid or any other control and limit its size.

**Expected behavior**
To have zoom and pan abilities even when resized.

**Desktop :**
 - OS: windows 
 - Browser Chrome,
 - Version 10

**Comment by beto-rodriguez** [comment] 2022-07-15 14:09
Hi and thanks for the issue!.

What do you mean with limit its size? did you set the `Width`/`Height` or the `MaxWidth`/`MaxHeight` properties?

Can you please share some code so I can reproduce the issue?

**Comment by EdenMeshulam28** [comment] 2022-07-17 05:00
Hi, 
Yes, I have set either the Width/Height or the MaxWidth/MaxHeight properties and then the Axes Min/Max is set to null (you see all of the chart values) and the zooming action is not working.

xaml code :
<lvc:CartesianChart x:Name="Chart"  Series="{Binding Series}"  ZoomMode="X"/>

in code behind I set only the serie to have values.

**Comment by beto-rodriguez** [comment] 2022-08-19 23:09
Seems to be working for me.

Am I missing something?

![Animation](https://user-images.githubusercontent.com/10853349/185717915-028b8b08-0e1f-4300-8f96-bc54d74b89a3.gif)

```xml
 <Grid Width="500" Height="500">
      <Grid.RowDefinitions>
          <RowDefinition Height="50"/>
          <RowDefinition Height="*"/>
      </Grid.RowDefinitions>
      
    <TextBlock Text="Use the mouse wheel to zoom in/out, click hold and drag to move panning"/>

    <lvc:CartesianChart
        Grid.Row="1"
        Series="{Binding SeriesCollection}"
        TooltipPosition="Hidden"
        ZoomMode="X"> <!-- mark -->
    </lvc:CartesianChart>
</Grid>
```

**Comment by Moskus** [comment] 2022-08-28 13:09
Perhaps this is what I'm experiencing as well?
I can't get zoom to work at all. The scroll wheel does nothing at all.

`        <Grid>
            <Grid.ColumnDefinitions>
                <ColumnDefinition Width="*"/>
                <ColumnDefinition Width="100"/>
            </Grid.ColumnDefinitions>

            <lvc:CartesianChart x:Name="chart"
                                Grid.Column="0"
                                Series="{Binding Series}"
                                AnimationsSpeed="0" 
                                TooltipPosition="Hidden"
                                ZoomMode="X"
                                />

            <ListView x:Name="lstView"
                Grid.Column="1"
                ItemsSource="{Binding Series}">
                <ListView.ItemTemplate>
                    <DataTemplate>
                        <TextCell Text="{Binding Name}"/>
                    </DataTemplate>
                </ListView.ItemTemplate>
            </ListView>
        </Grid>`

**Comment by beto-rodriguez** [comment] 2022-11-23 19:34
I am not able to reproduce this issue, I will close this for now, please feel free to reply with a repository that has the issue.

Thanks for the report and let me know if you find any evidence that the issue is in this library, I suspect that the issue might be on your side.

**Closed by beto-rodriguez** 2022-11-23 19:34 UTC
Labels: more info required, not verified
