### ISSUE TITLE
Observable Point updates at rate lower than app FPS

### ISSUE THREAD

**Issue by JacobPalecki** [beto-rodriguez/LiveCharts2#1027] opened 2023-05-22 21:34 UTC
**Describe the bug**
Observable Point seems to update on chart at a rate lower than the application FPS, when the properties of the C# observable point object are changed at a higher rate than application FPS.

**To Reproduce**
1. Create a simple Cartesian Chart.
2. Create an observable point bound to the chart with animations disabled.
3. Update the observable point at 1000hz via whatever mechanism you like.
4. Watch the observable point not update as fast as the app FPS.

**Expected behavior**
Since the Observable Point is being updated at a rate higher than the application FPS, I'd expect each frame of the application to show a new location of the Observable Point.

**Screenshots**
Video:
https://streamable.com/ybpuj6

On the left is my new avalonia app using LiveCharts. Mouse move from 1000hz mouse is used to change observable point. Logging confirms the observable point being updated every ms.
On the right is the same logic implemented in an old Windows Forms program (what I'm trying to replace with livecharts.) It's forced to run at 100 FPS.
The video is only 60 FPS and doesn't perfectly capture how much better the Windows Forms program looks on my 240hz monitor. But I still think it can be seen when the point moves rightward on the charts and falls back to the left. The Windows Forms program seems to update the point each frame whereas LiveCharts does not.
**Desktop (please complete the following information):**
 - OS: Windows 11

**Additional context**
I have a feeling an expert in LiveCharts might just look at my video and know what needs to be done.

**Comment by beto-rodriguez** [comment] 2023-08-21 21:57
The problem is that LiveCharts is not updated every time the data changes, it is updated once every interval (default is 50ms), this is controlled by the [UpdaterTrottler](https://lvcharts.com/docs/Maui/2.0.0-beta.900/Overview.Animations#updaterthrottler-property) property, reducing this property interval could improve your case, there is also https://github.com/beto-rodriguez/LiveCharts2/issues/1027, maybe we need a way to disable the throttler and just update on every call, but that would require more work from your side, since maybe you would require to remove the observable stuffs and just call a chart update every time you need it.

**Comment by beto-rodriguez** [comment] 2024-10-16 19:53
I will close this for now since this limitation is by design.

Additionally, we can reduce the [UpdaterTrottler](https://lvcharts.com/docs/Maui/2.0.0-beta.900/Overview.Animations#updaterthrottler-property) to get faster updates, but I think that the real solution in these cases is to completely disable animations, sadly the library is not designed for that, maybe in a future we could add this feature.

**Closed by beto-rodriguez** 2024-10-16 19:53 UTC
Labels: requires more research, priority 1
