### ISSUE TITLE
`LineSeries` tooltip not visible when using `DateTimePoint`

### ISSUE THREAD

**Issue by BlueDotBrigadeFounder** [beto-rodriguez/LiveCharts2#402] opened 2022-02-17 22:37 UTC
**Describe the bug**
Tool tip displays as expected for `LineSeries<float>` but not when you use the **exact same code** for `LineSeries<DateTimePoint>`.  Any guidance you can provide would be appreciated.

**To Reproduce**

1. Display a simple line series.
2. Mouse over a data point.

In XAML:
```XAML
        <lvc:CartesianChart x:Name="CartesianChart" Grid.Row="0" Grid.Column="0"
            XAxes="{Binding XAxes}"
            YAxes="{Binding YAxes}"
            Series="{Binding Series}"
            TooltipPosition="Top"/>
```

In the constructor:
```C#
LiveCharts.Configure(
settings => settings
	.AddDefaultMappers()
	.AddSkiaSharp()
	.AddDarkTheme());
```

When the `Series` property is called, the following is returned:
```C#
private ISeries[] GetSeries(ImmutableArray<IRecord> records)
{
	var values = new ObservableCollection<float>();
               
         // Does not work
	// var values = new ObservableCollection<DateTimePoint>();

	foreach (var record in records)
	{
		values.Add(record.value);

                              // Does not work
		// values.Add(new DateTimePoint(record.CreatedAt, record.value));
	}

	return new ISeries[]
	{
		// Does not work
		// new LineSeries<DateTimePoint>

		// works
		new LineSeries<float>
		{
			Name = "SeriesName",
			Values = values,
			TooltipLabelFormatter = (chartPoint) => $"TOOLTIP: {chartPoint.Context.Series.Name}: {chartPoint.PrimaryValue}",
		}
	};
```

**Expected behavior**
*  `LineSeries<float>` displays the tooltip as expected when you mouse over a data point.

**Actual Behavior**
* Using `LineSeries<DateTimePoint>` and the exact same code... a tooltip is not displayed.

**Screenshots**

 - OS: Windows 10 Pro, 64 bit, Version 21H1, Build 19043.1526
 - .NET Framework: 4.8
 - NuGet package: 2.0.0-beta.90 

**Additional context**

- None at this time.

**Comment by langejay** [comment] 2022-02-21 03:02
Related to the issue I raised in #393?  Is your x axis using 'large numbers'?

**Comment by Pressacco** [comment] 2022-02-21 16:16
Thanks for the heads up about #393. 

The dapoints are of type `DateTimePoint`. My x-axis are date / time values.

**Comment by langejay** [comment] 2022-02-22 02:56
No worries, I figured it might be related as we also store the data in Time/Date and came across a similar/same issue.  I then changed the axis to values to expose the issue #393 :-).

**Comment by Pressacco** [comment] 2022-02-26 11:56
# Root Cause

- My `DateTime` values are sometimes periodic, and other times there can be a random amount of time (milliseconds to hours) between data points.
- I had incorrectly assumed that for `DateTimePoint` `LineSeries` graphs there would be a one-to-one relationship between data points & tooltips.
- After reviewing the [DateTimeScaled sample code][A], I realized that _LiveCharts2_ appears to be using a grouping mechanism to determine which tool tips are displayed.
   - The mechanism appears to be controlled by an x-axis `UnitWidth`.  A property that had **not** been set in my code.

```C#
this.XAxes = new Axis[]
{
   new Axis
   {
      Name = value,
      Labeler = point => new DateTime((long)point).ToString("hh:mm:ss"),
      LabelsRotation = 15,
   }
}
```

# Solution

-  For my dataset:
   - omitting `UnitWidth` resulted in no tool tips being displayed
   - `UnitWidth=1` resulted in no tool tips being displayed
- You need to specify an x-axis `UnitWidth` value that is appropriate for your data set.  The LiveCharts2 documentation says the default value is `1`.
   -  Choose the wrong value and... no tooltip will be displayed.

```C#
this.XAxes = new Axis[]
{
   new Axis
   {
      Name = value,
      Labeler = point => new DateTime((long)point).ToString("hh:mm:ss"),
      LabelsRotation = 15,
      UnitWidth = TimeSpan.FromSeconds(10).Ticks, // set this to a value that is appropriate for your data set
   }
}
```

<img width="332" alt="image" src="https://user-images.githubusercontent.com/5507864/155841902-ce01eda8-2916-49fe-a21a-c8a9613374ae.png">


[A]: https://github.com/beto-rodriguez/LiveCharts2/blob/92578602760fa5089ff2f638e52b3508ce57c6b2/samples/ViewModelsSamples/Axes/DateTimeScaled/ViewModel.cs

**Comment by beto-rodriguez** [comment] 2022-04-26 18:25
Thanks for the issue and the feedback.

Yes you are right @Pressacco The `UnitWidth` is necessary in this case, it fixes your issue. I am thinking in a way to simplify this but I think that it will be enough if we explain better in the docs how to handle `DateTime` plots, I extended the docs in the referenced commits, and [changed](https://github.com/beto-rodriguez/LiveCharts2/commit/e36fedb05dd306cc5590caaeddb69a80ac33384e) the `DateTime`/`TimeSpan` samples to explain that this step is required.

About your second query about the repeated point in the tooltip, I also agree, we normally only want to see the closest point to the pointer, so that is how the library will behave by default in the next release, but we could also configure the chart to behave as it does now. 

I will close this for now since you found a solution for your issue, your second issue will be gone when you update to the next release of the library.

**Closed by beto-rodriguez** 2022-04-26 18:25 UTC

**Comment by Pressacco** [comment] 2022-04-26 23:50
Thank you for the response @beto-rodriguez. 

BTW - cool library 👍
