### ISSUE TITLE
GeometryVisual disappeared after refresh the chart

### ISSUE THREAD

**Issue by Zhao-Michael** [beto-rodriguez/LiveCharts2#1400] opened 2023-12-12 01:23 UTC
**Describe the bug**
The GeometryVisual (Small Black Rectangle in below picture) will disappear at the third refresh.

**To Reproduce**
Please download the simple project zip.
Run the project, click 'Refresh' Button, at the third click, the small black rectangle will disappear 

**Expected behavior**
The GeometryVisual should be always visible

**Screenshots**

![image](https://github.com/beto-rodriguez/LiveCharts2/assets/15730936/cc9427ef-ade0-498f-9eac-eadc224a2990)

**Desktop (please complete the following information):**
 - OS: Windows
 - WPF .net8
 - Version 10

**Additional context**
NA
[LiveCharts2Demo.zip](https://github.com/beto-rodriguez/LiveCharts2/files/13642529/LiveCharts2Demo.zip)

**Comment by Zhao-Michael** [comment] 2023-12-12 01:50
I believe it may cause by the order of VisualElements... It's not stable to render the VisualElements in CartesianChart.

**Comment by beto-rodriguez** [comment] 2024-09-15 20:52
Hello

It seems that it is an issue in the way paints are added to the canvas, the black rectangle is there, it is just behind the other rectangles.

I am not completely sure in this case why at the third time it goes back, but you can set the `ZIndex` to ensure that your last rectangle is above all:

```c#
var rectangleVisual = new GeometryVisual<RectangleGeometry>
{
    Fill = new SolidColorPaint(s_black) { ZIndex = 99 },
};
```

And that;s it, now that rectangle is always on top.


![zindez](https://github.com/user-attachments/assets/a5b8f3e1-e99e-4bf9-833f-927554abd011)

I will close this for now since it seems that the issue is solved, but feel free to reply if there is something I can do to help.

**Closed by beto-rodriguez** 2024-09-15 20:52 UTC
