### ISSUE TITLE
KeyNotFoundException Rendering Pie Chart into Skia view

### ISSUE THREAD

**Issue by girlpunk** [beto-rodriguez/LiveCharts2#1323] opened 2023-10-20 19:30 UTC
**Describe the bug**
```
System.Collections.Generic.KeyNotFoundException: The given key '0' was not present in the dictionary.
at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
at LiveChartsCore.Kernel.Stacker`1.GetStack(ChartPoint point, Int32 seriesStackPosition)
at LiveChartsCore.Measure.StackPosition`1.GetStack(ChartPoint point)
at LiveChartsCore.PieSeries`5.Invalidate(Chart`1 chart)
at LiveChartsCore.Chart`1.AddVisual(ChartElement`1 element)
at LiveChartsCore.PieChart`1.Measure()
at LiveChartsCore.SkiaSharpView.SKCharts.InMemorySkiaSharpChart.DrawOnCanvas(SKCanvas canvas, SKSurface surface, Boolean clearCanvasOnBeginDraw)
at LiveChartsCore.SkiaSharpView.SKCharts.InMemorySkiaSharpChart.GetImage()
```

**To Reproduce**
```
// Get all the values of an enum
var series = ((MyEnumType[]) Enum.GetValues(typeof(MyEnumType)))
    // Take a list, group it by a property of that enum, and count the groupings
    .GroupJoin(
        rows,
        static myEnumType=> myEnumType,
        row => row.propertyOfEnumType,
        static (prop, rowList) => new { prop, count = rowList.Count() }
    )
    // Sort the groupings by the property value, to ensure they always appear in the same order
    .OrderBy(static g => g.prop)
    // Create a new PieSeries from each grouping
    .Select(
        g => new PieSeries<int>
        {
            // Single value with the number of rows having that enum set
            Values = new[] { g.count },
            // Get a descriptive label for the value
            Name = g.prop.GetEnumDescription(),
            // Give it a colour
            Fill = new SolidColorPaint(
                SKColor.Parse(
                    EnumColours[g.prop]
                )
            ),
            // Make the chart look nice
            Pushout = 8,
        }
    );

// Create a new pie chart
var chart = new SKPieChart
{
    // Render at a higher resolution, so the chart looks good when zoomed in
    Width = (int) size.Width * 4,
    Height = (int) size.Height * 4,
    Background = SKColors.Transparent,
    Series = series,
};

// Get an image of the chart, to put into Skia
using var image = chart.GetImage(); // <-- Exception thrown here
using var data = image.Encode();
return data.ToArray();
```

**Expected behavior**
The chart should render

**Screenshots**
Expected outcome is something like this
![image](https://github.com/beto-rodriguez/LiveCharts2/assets/161093/ee4d2344-88a0-43bc-a79f-3a899bd8c04c)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Edge 117
 - SkiaSharp: 2.88.6
 - QuestPDF: 2022.12.6

**Additional context**
Did some testing with different versions, this works correctly up to `2.0.0-beta.920`, but is broken in `2.0.0.rc1`

**Comment by beto-rodriguez** [comment] 2023-10-28 01:11
Hi and thanks for the report.

In general, it is not a good idea to use en `IEnumerable` as the data source, because that expression is evaluated every time the chart is rendered, I was able to reproduce, but you can easily fixe it by materializing your LINQ expression:

```c#
var series = ((MyEnumType[]) Enum.GetValues(typeof(MyEnumType)))
    // Take a list, group it by a property of that enum, and count the groupings
    .GroupJoin(...)
    // Sort the groupings by the property value, to ensure they always appear in the same order
    .OrderBy(static g => g.prop)
    // Create a new PieSeries from each grouping
    .Select(...)
    .ToArray();
```

This needs better docs, at this point the type `IEnumerable` seems the best choice for the library, but it seems that it also causes some confuision.

I will close this for now but feel free to reply if that does not fix the issue or if you think that the library should work with the `IEnumerable` type.

**Closed by beto-rodriguez** 2023-10-28 01:11 UTC
