### ISSUE TITLE
Avalonia 11.0 preview2 bug

### ISSUE THREAD

**Issue by laolarou726** [beto-rodriguez/LiveCharts2#680] opened 2022-10-10 20:59 UTC
**Describe the bug**

Livecharts will throw the exception, and Application will stuck:
```

[Visual]Exception in render loop: 'System.InvalidOperationException: Call from invalid thread
   at Avalonia.Threading.Dispatcher.VerifyAccess() in /_/src/Avalonia.Base/Threading/Dispatcher.cs:line 48
   at Avalonia.Rendering.Composition.Compositor.InvokeBeforeNextCommit(Action`1 action) in /_/src/Avalonia.Base/Rendering/Composition/Compositor.cs:line 135
   at Avalonia.Rendering.Composition.CompositingRenderer.AddDirty(IVisual visual) in /_/src/Avalonia.Base/Rendering/Composition/CompositingRenderer.cs:line 83
   at LiveChartsCore.SkiaSharpView.Avalonia.MotionCanvas.CustomDrawOp.Render(IDrawingContextImpl context)
   at Avalonia.Rendering.SceneGraph.CustomDrawOperation.Render(IDrawingContextImpl context) in /_/src/Avalonia.Base/Rendering/SceneGraph/CustomDrawOperation.cs:line 30
   at Avalonia.Rendering.Composition.Drawing.CompositionDrawList.Render(CompositorDrawingContextProxy canvas) in /_/src/Avalonia.Base/Rendering/Composition/Drawing/CompositionDrawList.cs:line 48
   at Avalonia.Rendering.Composition.Server.ServerCompositionDrawListVisual.RenderCore(CompositorDrawingContextProxy canvas, Rect currentTransformedClip) in /_/src/Avalonia.Base/Rendering/Composition/Server/ServerCompositionDrawListVisual.cs:line 66
   at Avalonia.Rendering.Composition.Server.ServerCompositionVisual.Render(CompositorDrawingContextProxy canvas, Rect currentTransformedClip) in /_/src/Avalonia.Base/Rendering/Composition/Server/ServerCompositionVisual.cs:line 58
   at Avalonia.Rendering.Composition.Server.ServerCompositionContainerVisual.RenderCore(CompositorDrawingContextProxy canvas, Rect currentTransformedClip) in /_/src/Avalonia.Base/Rendering/Composition/Server/ServerCompositionContainerVisual.cs:line 19
   at Avalonia.Rendering.Composition.Server.ServerCompositionVisual.Render(CompositorDrawingContextProxy canvas, Rect currentTransformedClip) in /_/src/Avalonia.Base/Rendering/Composition/Server/ServerCompositionVisual.cs:line 58
   at Avalonia.Rendering.Composition.Server.ServerCompositionContainerVisual.RenderCore(CompositorDrawingContextProxy canvas, Rect currentTransformedClip) in /_/src/Avalonia.Base/Rendering/Composition/Server/ServerCompositionContainerVisual.cs:line 19
   at Avalonia.Rendering.Composition.Server.ServerCompositionVisual.Render(CompositorDrawingContextProxy canvas, Rect currentTransformedClip) in /_/src/Avalonia.Base/Rendering/Composition/Server/ServerCompositionVisual.cs:line 58
   at Avalonia.Rendering.Composition.Server.ServerCompositionContainerVisual.RenderCore(CompositorDrawingContextProxy canvas, Rect currentTransformedClip) in /_/src/Avalonia.Base/Rendering/Composition/Server/ServerCompositionContainerVisual.cs:line 19
   at Avalonia.Rendering.Composition.Server.ServerCompositionVisual.Render(CompositorDrawingContextProxy canvas, Rect currentTransformedClip) in /_/src/Avalonia.Base/Rendering/Composition/Server/ServerCompositionVisual.cs:line 58
   at Avalonia.Rendering.Composition.Server.ServerCompositionContainerVisual.RenderCore(CompositorDrawingContextProxy canvas, Rect currentTransformedClip) in /_/src/Avalonia.Base/Rendering/Composition/Server/ServerCompositionContainerVisual.cs:line 19
   at Avalonia.Rendering.Composition.Server.ServerCompositionVisual.Render(CompositorDrawingContextProxy canvas, Rect currentTransformedClip) in /_/src/Avalonia.Base/Rendering/Composition/Server/ServerCompositionVisual.cs:line 58
   at Avalonia.Rendering.Composition.Server.ServerCompositionContainerVisual.RenderCore(CompositorDrawingContextProxy canvas, Rect currentTransformedClip) in /_/src/Avalonia.Base/Rendering/Composition/Server/ServerCompositionContainerVisual.cs:line 19
   at Avalonia.Rendering.Composition.Server.ServerCompositionVisual.Render(CompositorDrawingContextProxy canvas, Rect currentTransformedClip) in /_/src/Avalonia.Base/Rendering/Composition/Server/ServerCompositionVisual.cs:line 58
   at Avalonia.Rendering.Composition.Server.ServerCompositionContainerVisual.RenderCore(CompositorDrawingContextProxy canvas, Rect currentTransformedClip) in /_/src/Avalonia.Base/Rendering/Composition/Server/ServerCompositionContainerVisual.cs:line 19
   at Avalonia.Rendering.Composition.Server.ServerCompositionVisual.Render(CompositorDrawingContextProxy canvas, Rect currentTransformedClip) in /_/src/Avalonia.Base/Rendering/Composition/Server/ServerCompositionVisual.cs:line 58
   at Avalonia.Rendering.Composition.Server.ServerCompositionContainerVisual.RenderCore(CompositorDrawingContextProxy canvas, Rect currentTransformedClip) in /_/src/Avalonia.Base/Rendering/Composition/Server/ServerCompositionContainerVisual.cs:line 19
   at Avalonia.Rendering.Composition.Server.ServerCompositionVisual.Render(CompositorDrawingContextProxy canvas, Rect currentTransformedClip) in /_/src/Avalonia.Base/Rendering/Composition/Server/ServerCompositionVisual.cs:line 58
   at Avalonia.Rendering.Composition.Server.ServerCompositionContainerVisual.RenderCore(CompositorDrawingContextProxy canvas, Rect currentTransformedClip) in /_/src/Avalonia.Base/Rendering/Composition/Server/ServerCompositionContainerVisual.cs:line 19
   at Avalonia.Rendering.Composition.Server.ServerCompositionVisual.Render(CompositorDrawingContextProxy canvas, Rect currentTransformedClip) in /_/src/Avalonia.Base/Rendering/Composition/Server/ServerCompositionVisual.cs:line 58
   at Avalonia.Rendering.Composition.Server.ServerCompositionContainerVisual.RenderCore(CompositorDrawingContextProxy canvas, Rect currentTransformedClip) in /_/src/Avalonia.Base/Rendering/Composition/Server/ServerCompositionContainerVisual.cs:line 19
   at Avalonia.Rendering.Composition.Server.ServerCompositionVisual.Render(CompositorDrawingContextProxy canvas, Rect currentTransformedClip) in /_/src/Avalonia.Base/Rendering/Composition/Server/ServerCompositionVisual.cs:line 58
   at Avalonia.Rendering.Composition.Server.ServerCompositionContainerVisual.RenderCore(CompositorDrawingContextProxy canvas, Rect currentTransformedClip) in /_/src/Avalonia.Base/Rendering/Composition/Server/ServerCompositionContainerVisual.cs:line 19
   at Avalonia.Rendering.Composition.Server.ServerCompositionVisual.Render(CompositorDrawingContextProxy canvas, Rect currentTransformedClip) in /_/src/Avalonia.Base/Rendering/Composition/Server/ServerCompositionVisual.cs:line 58
   at Avalonia.Rendering.Composition.Server.ServerCompositionContainerVisual.RenderCore(CompositorDrawingContextProxy canvas, Rect currentTransformedClip) in /_/src/Avalonia.Base/Rendering/Composition/Server/ServerCompositionContainerVisual.cs:line 19
   at Avalonia.Rendering.Composition.Server.ServerCompositionVisual.Render(CompositorDrawingContextProxy canvas, Rect currentTransformedClip) in /_/src/Avalonia.Base/Rendering/Composition/Server/ServerCompositionVisual.cs:line 58
   at Avalonia.Rendering.Composition.Server.ServerCompositionContainerVisual.RenderCore(CompositorDrawingContextProxy canvas, Rect currentTransformedClip) in /_/src/Avalonia.Base/Rendering/Composition/Server/ServerCompositionContainerVisual.cs:line 19
   at Avalonia.Rendering.Composition.Server.ServerCompositionVisual.Render(CompositorDrawingContextProxy canvas, Rect currentTransformedClip) in /_/src/Avalonia.Base/Rendering/Composition/Server/ServerCompositionVisual.cs:line 58
   at Avalonia.Rendering.Composition.Server.ServerCompositionContainerVisual.RenderCore(CompositorDrawingContextProxy canvas, Rect currentTransformedClip) in /_/src/Avalonia.Base/Rendering/Composition/Server/ServerCompositionContainerVisual.cs:line 19
   at Avalonia.Rendering.Composition.Server.ServerCompositionVisual.Render(CompositorDrawingContextProxy canvas, Rect currentTransformedClip) in /_/src/Avalonia.Base/Rendering/Composition/Server/ServerCompositionVisual.cs:line 58
   at Avalonia.Rendering.Composition.Server.ServerCompositionContainerVisual.RenderCore(CompositorDrawingContextProxy canvas, Rect currentTransformedClip) in /_/src/Avalonia.Base/Rendering/Composition/Server/ServerCompositionContainerVisual.cs:line 19
   at Avalonia.Rendering.Composition.Server.ServerCompositionVisual.Render(CompositorDrawingContextProxy canvas, Rect currentTransformedClip) in /_/src/Avalonia.Base/Rendering/Composition/Server/ServerCompositionVisual.cs:line 58
   at Avalonia.Rendering.Composition.Server.ServerCompositionContainerVisual.RenderCore(CompositorDrawingContextProxy canvas, Rect currentTransformedClip) in /_/src/Avalonia.Base/Rendering/Composition/Server/ServerCompositionContainerVisual.cs:line 19
   at Avalonia.Rendering.Composition.Server.ServerCompositionVisual.Render(CompositorDrawingContextProxy canvas, Rect currentTransformedClip) in /_/src/Avalonia.Base/Rendering/Composition/Server/ServerCompositionVisual.cs:line 58
   at Avalonia.Rendering.Composition.Server.ServerCompositionContainerVisual.RenderCore(CompositorDrawingContextProxy canvas, Rect currentTransformedClip) in /_/src/Avalonia.Base/Rendering/Composition/Server/ServerCompositionContainerVisual.cs:line 19
   at Avalonia.Rendering.Composition.Server.ServerCompositionVisual.Render(CompositorDrawingContextProxy canvas, Rect currentTransformedClip) in /_/src/Avalonia.Base/Rendering/Composition/Server/ServerCompositionVisual.cs:line 58
   at Avalonia.Rendering.Composition.Server.ServerCompositionContainerVisual.RenderCore(CompositorDrawingContextProxy canvas, Rect currentTransformedClip) in /_/src/Avalonia.Base/Rendering/Composition/Server/ServerCompositionContainerVisual.cs:line 19
   at Avalonia.Rendering.Composition.Server.ServerCompositionVisual.Render(CompositorDrawingContextProxy canvas, Rect currentTransformedClip) in /_/src/Avalonia.Base/Rendering/Composition/Server/ServerCompositionVisual.cs:line 58
   at Avalonia.Rendering.Composition.Server.ServerCompositionContainerVisual.RenderCore(CompositorDrawingContextProxy canvas, Rect currentTransformedClip) in /_/src/Avalonia.Base/Rendering/Composition/Server/ServerCompositionContainerVisual.cs:line 19
   at Avalonia.Rendering.Composition.Server.ServerCompositionVisual.Render(CompositorDrawingContextProxy canvas, Rect currentTransformedClip) in /_/src/Avalonia.Base/Rendering/Composition/Server/ServerCompositionVisual.cs:line 58
   at Avalonia.Rendering.Composition.Server.ServerCompositionContainerVisual.RenderCore(CompositorDrawingContextProxy canvas, Rect currentTransformedClip) in /_/src/Avalonia.Base/Rendering/Composition/Server/ServerCompositionContainerVisual.cs:line 19
   at Avalonia.Rendering.Composition.Server.ServerCompositionVisual.Render(CompositorDrawingContextProxy canvas, Rect currentTransformedClip) in /_/src/Avalonia.Base/Rendering/Composition/Server/ServerCompositionVisual.cs:line 58
   at Avalonia.Rendering.Composition.Server.ServerCompositionContainerVisual.RenderCore(CompositorDrawingContextProxy canvas, Rect currentTransformedClip) in /_/src/Avalonia.Base/Rendering/Composition/Server/ServerCompositionContainerVisual.cs:line 19
   at Avalonia.Rendering.Composition.Server.ServerCompositionVisual.Render(CompositorDrawingContextProxy canvas, Rect currentTransformedClip) in /_/src/Avalonia.Base/Rendering/Composition/Server/ServerCompositionVisual.cs:line 58
   at Avalonia.Rendering.Composition.Server.ServerCompositionContainerVisual.RenderCore(CompositorDrawingContextProxy canvas, Rect currentTransformedClip) in /_/src/Avalonia.Base/Rendering/Composition/Server/ServerCompositionContainerVisual.cs:line 19
   at Avalonia.Rendering.Composition.Server.ServerCompositionVisual.Render(CompositorDrawingContextProxy canvas, Rect currentTransformedClip) in /_/src/Avalonia.Base/Rendering/Composition/Server/ServerCompositionVisual.cs:line 58
   at Avalonia.Rendering.Composition.Server.ServerCompositionContainerVisual.RenderCore(CompositorDrawingContextProxy canvas, Rect currentTransformedClip) in /_/src/Avalonia.Base/Rendering/Composition/Server/ServerCompositionContainerVisual.cs:line 19
   at Avalonia.Rendering.Composition.Server.ServerCompositionVisual.Render(CompositorDrawingContextProxy canvas, Rect currentTransformedClip) in /_/src/Avalonia.Base/Rendering/Composition/Server/ServerCompositionVisual.cs:line 58
   at Avalonia.Rendering.Composition.Server.ServerCompositionContainerVisual.RenderCore(CompositorDrawingContextProxy canvas, Rect currentTransformedClip) in /_/src/Avalonia.Base/Rendering/Composition/Server/ServerCompositionContainerVisual.cs:line 19
   at Avalonia.Rendering.Composition.Server.ServerCompositionVisual.Render(CompositorDrawingContextProxy canvas, Rect currentTransformedClip) in /_/src/Avalonia.Base/Rendering/Composition/Server/ServerCompositionVisual.cs:line 58
   at Avalonia.Rendering.Composition.Server.ServerCompositionContainerVisual.RenderCore(CompositorDrawingContextProxy canvas, Rect currentTransformedClip) in /_/src/Avalonia.Base/Rendering/Composition/Server/ServerCompositionContainerVisual.cs:line 19
   at Avalonia.Rendering.Composition.Server.ServerCompositionVisual.Render(CompositorDrawingContextProxy canvas, Rect currentTransformedClip) in /_/src/Avalonia.Base/Rendering/Composition/Server/ServerCompositionVisual.cs:line 58
   at Avalonia.Rendering.Composition.Server.ServerCompositionContainerVisual.RenderCore(CompositorDrawingContextProxy canvas, Rect currentTransformedClip) in /_/src/Avalonia.Base/Rendering/Composition/Server/ServerCompositionContainerVisual.cs:line 19
   at Avalonia.Rendering.Composition.Server.ServerCompositionVisual.Render(CompositorDrawingContextProxy canvas, Rect currentTransformedClip) in /_/src/Avalonia.Base/Rendering/Composition/Server/ServerCompositionVisual.cs:line 58
   at Avalonia.Rendering.Composition.Server.ServerCompositionContainerVisual.RenderCore(CompositorDrawingContextProxy canvas, Rect currentTransformedClip) in /_/src/Avalonia.Base/Rendering/Composition/Server/ServerCompositionContainerVisual.cs:line 19
   at Avalonia.Rendering.Composition.Server.ServerCompositionVisual.Render(CompositorDrawingContextProxy canvas, Rect currentTransformedClip) in /_/src/Avalonia.Base/Rendering/Composition/Server/ServerCompositionVisual.cs:line 58
   at Avalonia.Rendering.Composition.Server.ServerCompositionContainerVisual.RenderCore(CompositorDrawingContextProxy canvas, Rect currentTransformedClip) in /_/src/Avalonia.Base/Rendering/Composition/Server/ServerCompositionContainerVisual.cs:line 19
   at Avalonia.Rendering.Composition.Server.ServerCompositionVisual.Render(CompositorDrawingContextProxy canvas, Rect currentTransformedClip) in /_/src/Avalonia.Base/Rendering/Composition/Server/ServerCompositionVisual.cs:line 58
   at Avalonia.Rendering.Composition.Server.ServerCompositionContainerVisual.RenderCore(CompositorDrawingContextProxy canvas, Rect currentTransformedClip) in /_/src/Avalonia.Base/Rendering/Composition/Server/ServerCompositionContainerVisual.cs:line 19
   at Avalonia.Rendering.Composition.Server.ServerCompositionVisual.Render(CompositorDrawingContextProxy canvas, Rect currentTransformedClip) in /_/src/Avalonia.Base/Rendering/Composition/Server/ServerCompositionVisual.cs:line 58
   at Avalonia.Rendering.Composition.Server.ServerCompositionContainerVisual.RenderCore(CompositorDrawingContextProxy canvas, Rect currentTransformedClip) in /_/src/Avalonia.Base/Rendering/Composition/Server/ServerCompositionContainerVisual.cs:line 19
   at Avalonia.Rendering.Composition.Server.ServerCompositionVisual.Render(CompositorDrawingContextProxy canvas, Rect currentTransformedClip) in /_/src/Avalonia.Base/Rendering/Composition/Server/ServerCompositionVisual.cs:line 58
   at Avalonia.Rendering.Composition.Server.ServerCompositionContainerVisual.RenderCore(CompositorDrawingContextProxy canvas, Rect currentTransformedClip) in /_/src/Avalonia.Base/Rendering/Composition/Server/ServerCompositionContainerVisual.cs:line 19
   at Avalonia.Rendering.Composition.Server.ServerCompositionVisual.Render(CompositorDrawingContextProxy canvas, Rect currentTransformedClip) in /_/src/Avalonia.Base/Rendering/Composition/Server/ServerCompositionVisual.cs:line 58
   at Avalonia.Rendering.Composition.Server.ServerCompositionContainerVisual.RenderCore(CompositorDrawingContextProxy canvas, Rect currentTransformedClip) in /_/src/Avalonia.Base/Rendering/Composition/Server/ServerCompositionContainerVisual.cs:line 19
   at Avalonia.Rendering.Composition.Server.ServerCompositionVisual.Render(CompositorDrawingContextProxy canvas, Rect currentTransformedClip) in /_/src/Avalonia.Base/Rendering/Composition/Server/ServerCompositionVisual.cs:line 58
   at Avalonia.Rendering.Composition.Server.ServerCompositionContainerVisual.RenderCore(CompositorDrawingContextProxy canvas, Rect currentTransformedClip) in /_/src/Avalonia.Base/Rendering/Composition/Server/ServerCompositionContainerVisual.cs:line 19
   at Avalonia.Rendering.Composition.Server.ServerCompositionVisual.Render(CompositorDrawingContextProxy canvas, Rect currentTransformedClip) in /_/src/Avalonia.Base/Rendering/Composition/Server/ServerCompositionVisual.cs:line 58
   at Avalonia.Rendering.Composition.Server.ServerCompositionContainerVisual.RenderCore(CompositorDrawingContextProxy canvas, Rect currentTransformedClip) in /_/src/Avalonia.Base/Rendering/Composition/Server/ServerCompositionContainerVisual.cs:line 19
   at Avalonia.Rendering.Composition.Server.ServerCompositionVisual.Render(CompositorDrawingContextProxy canvas, Rect currentTransformedClip) in /_/src/Avalonia.Base/Rendering/Composition/Server/ServerCompositionVisual.cs:line 58
   at Avalonia.Rendering.Composition.Server.ServerCompositionContainerVisual.RenderCore(CompositorDrawingContextProxy canvas, Rect currentTransformedClip) in /_/src/Avalonia.Base/Rendering/Composition/Server/ServerCompositionContainerVisual.cs:line 19
   at Avalonia.Rendering.Composition.Server.ServerCompositionVisual.Render(CompositorDrawingContextProxy canvas, Rect currentTransformedClip) in /_/src/Avalonia.Base/Rendering/Composition/Server/ServerCompositionVisual.cs:line 58
   at Avalonia.Rendering.Composition.Server.ServerCompositionContainerVisual.RenderCore(CompositorDrawingContextProxy canvas, Rect currentTransformedClip) in /_/src/Avalonia.Base/Rendering/Composition/Server/ServerCompositionContainerVisual.cs:line 19
   at Avalonia.Rendering.Composition.Server.ServerCompositionVisual.Render(CompositorDrawingContextProxy canvas, Rect currentTransformedClip) in /_/src/Avalonia.Base/Rendering/Composition/Server/ServerCompositionVisual.cs:line 58
   at Avalonia.Rendering.Composition.Server.ServerCompositionContainerVisual.RenderCore(CompositorDrawingContextProxy canvas, Rect currentTransformedClip) in /_/src/Avalonia.Base/Rendering/Composition/Server/ServerCompositionContainerVisual.cs:line 19
   at Avalonia.Rendering.Composition.Server.ServerCompositionVisual.Render(CompositorDrawingContextProxy canvas, Rect currentTransformedClip) in /_/src/Avalonia.Base/Rendering/Composition/Server/ServerCompositionVisual.cs:line 58
   at Avalonia.Rendering.Composition.Server.ServerCompositionContainerVisual.RenderCore(CompositorDrawingContextProxy canvas, Rect currentTransformedClip) in /_/src/Avalonia.Base/Rendering/Composition/Server/ServerCompositionContainerVisual.cs:line 19
   at Avalonia.Rendering.Composition.Server.ServerCompositionVisual.Render(CompositorDrawingContextProxy canvas, Rect currentTransformedClip) in /_/src/Avalonia.Base/Rendering/Composition/Server/ServerCompositionVisual.cs:line 58
   at Avalonia.Rendering.Composition.Server.ServerCompositionContainerVisual.RenderCore(CompositorDrawingContextProxy canvas, Rect currentTransformedClip) in /_/src/Avalonia.Base/Rendering/Composition/Server/ServerCompositionContainerVisual.cs:line 19
   at Avalonia.Rendering.Composition.Server.ServerCompositionVisual.Render(CompositorDrawingContextProxy canvas, Rect currentTransformedClip) in /_/src/Avalonia.Base/Rendering/Composition/Server/ServerCompositionVisual.cs:line 58
   at Avalonia.Rendering.Composition.Server.ServerCompositionContainerVisual.RenderCore(CompositorDrawingContextProxy canvas, Rect currentTransformedClip) in /_/src/Avalonia.Base/Rendering/Composition/Server/ServerCompositionContainerVisual.cs:line 19
   at Avalonia.Rendering.Composition.Server.ServerCompositionVisual.Render(CompositorDrawingContextProxy canvas, Rect currentTransformedClip) in /_/src/Avalonia.Base/Rendering/Composition/Server/ServerCompositionVisual.cs:line 58
   at Avalonia.Rendering.Composition.Server.ServerCompositionContainerVisual.RenderCore(CompositorDrawingContextProxy canvas, Rect currentTransformedClip) in /_/src/Avalonia.Base/Rendering/Composition/Server/ServerCompositionContainerVisual.cs:line 19
   at Avalonia.Rendering.Composition.Server.ServerCompositionVisual.Render(CompositorDrawingContextProxy canvas, Rect currentTransformedClip) in /_/src/Avalonia.Base/Rendering/Composition/Server/ServerCompositionVisual.cs:line 58
   at Avalonia.Rendering.Composition.Server.ServerCompositionTarget.Render() in /_/src/Avalonia.Base/Rendering/Composition/Server/ServerCompositionTarget.cs:line 127
   at Avalonia.Rendering.Composition.Server.ServerCompositor.RenderCore() in /_/src/Avalonia.Base/Rendering/Composition/Server/ServerCompositor.cs:line 116
   at Avalonia.Rendering.Composition.Server.ServerCompositor.Render() in /_/src/Avalonia.Base/Rendering/Composition/Server/ServerCompositor.cs:line 104
   at Avalonia.Rendering.RenderLoop.TimerTick(TimeSpan time) in /_/src/Avalonia.Base/Rendering/RenderLoop.cs:line 145'(RenderLoop #9350850)

```

**To Reproduce**
1. Create a new chart in the XAML
2. Create a method to update data in the Task with Dispatcher
3. Compile and run
4. Application will be stuck

**Expected behavior**

1. Data will show on the chart and the application will not be stuck

**Screenshots**

<img width="676" alt="image" src="https://user-images.githubusercontent.com/25716486/194951132-4625bf42-79ca-4dcc-864f-66c5d4b7bb45.png">

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 11
 - LiveCharts2 Version: 2.0.0-beta.501-11.0.0-preview1

**Additional context**

**Comment by beto-rodriguez** [comment] 2022-10-12 19:32
Strange, the library has a sample where it updates the data in the dispatcher, no issues there:

https://github.com/beto-rodriguez/LiveCharts2/blob/avalonia-preview/samples/AvaloniaSample/General/MultiThreading2/View.axaml.cs

Am I missing something? can you please provide some code so I can reproduce?

**Comment by hahagu** [comment] 2022-10-12 19:34
> Strange, the library has a sample where it updates the data in the dispatcher, no issues there:
> 
> [`avalonia-preview`/samples/AvaloniaSample/General/MultiThreading2/View.axaml.cs](https://github.com/beto-rodriguez/LiveCharts2/blob/avalonia-preview/samples/AvaloniaSample/General/MultiThreading2/View.axaml.cs?rgh-link-date=2022-10-12T19%3A32%3A14Z)
> 
> Am I missing something? can you please provide some code so I can reproduce?

It only happens on the 11.0.0 Preview 2 version of Avalonia atm, not the Preview 1 version.
I'm using an implementation of your automatic updates for reference.
Should work the same way.

**Comment by hahagu** [comment] 2022-10-12 19:38
It's a bummer, because preview 1 of avalonia also has a `collection modified` bug which makes it sort of unusable 😅

**Comment by beto-rodriguez** [comment] 2022-10-12 21:08
It should be fixed in this version https://www.nuget.org/packages/LiveChartsCore.SkiaSharpView.Avalonia/2.0.0-beta.502-11.0.0-preview2, please let me know if the issue is gone for you.

**Comment by laolarou726** [comment] 2022-10-12 21:16
The issue has been fixed! Thank you so much!

**Comment by beto-rodriguez** [comment] 2022-10-12 21:39
Glad to rea that!

**Closed by beto-rodriguez** 2022-10-12 21:39 UTC
Labels: more info required
