### ISSUE TITLE
[Ask or Bug] How to remove a previous data in the UI when changing (clear and then add) the whole chart values ? (Seems to be the ScatterSeries problem)

### ISSUE THREAD

**Issue by kshfire** [beto-rodriguez/LiveCharts2#1164] opened 2023-08-10 00:19 UTC
**Describe the bug**

When I changed whole chart values by the WPF button, sometimes the previous graph was remained.
To avoid this problem, I added a delay after clearing the Chart Value and then added new Values for displaying.
But, it is not perfect to solve this problem.

** My approach but not perfect.. :  When change chart values
  -  observableValue.Clear();
  - Thread.Sleep(xxx);               // To avoid afterimage problem,  but, it is not a solution. I want to know how to clearly clear the plot and add new data set.
  - Using for loop
     observableValue.Add ( xxx );

=> The Previous graph data are removed. But, the previous plot is remained on the UI.

Is there a more reliable way to avoid previous afterimages when chaning the whole data of the Chart ?
Or, How to erase/clear/reset UI chart canvas ?  Because a previous plot graphics is also remained so I want to know how to erase it.

I'm sorry, there is no capture images.

=====================
I've searched whole issues in the github.  Below seems to be similiar to my case...

https://github.com/beto-rodriguez/LiveCharts2/issues/503

I've done a lot of tests.
**ScatterSeries has this problem.  Fortunately, LineSeries has no this problem**, so I replaced ScatterSeries with LineSeries temporarily.

※ Animation behavior (EasingFunction) of LineSeries is different with ScatterSeries. 
   When I add a new value to LineSeries, the graph is animated too much unlike to ScatterSeries case.
   Thus, I regrettably turned off animation effect in the LineSeries.  Are there any safe method to add data for LineSeries without too much plot animated motion ?  I still need lots of study of the LiveCharts2 usage  ^^.

**Comment by beto-rodriguez** [comment] 2023-08-15 00:01
Hi, I just tried to reproduce the issue with no luck :(

Can you please provide a minimal repository/zip/code that illustrates what you are doing? then I will be able to help you better.

**Comment by beto-rodriguez** [comment] 2023-08-27 00:49
I will close this for now, feel free to re-open if you find any new evidence with the isuse.

**Comment by ianmichaelbrown** [comment] 2023-09-22 14:44
@beto-rodriguez I don't think I have the ability to re-open this issue, so am just leaving this comment for you to action however you see fit. :-)

Hi Alberto.  Sorry for the delay, but I have now managed to reproduce this issue and have linked below a sample .NET MAUI solution.  This was created on VS2022 and has been tested as both a Windows 10 Desktop and an Android app.

Issue Summary: Given a bar graph consisting of ‘DateTimePoint’ values, after updating the graph values, **previous values will remain in the UI**, if the graph has previously been hidden, then made visible again.

Steps to reproduce:
1.	Run the solution **using VS2022**; this opens displaying a set of sample data, with the ability to update and clear the data, as well as toggling its visibility.
2.	Verify that the Update and Clear buttons work as expected.
3.	Identify a small graph bar and make note of its value using its tooltip.
4.	Click on Toggle Visibility to hide the data.
5.	Click again to show the data.
6.	Note that Clear **does not clear the UI**, though _does_ clear the underlying data (there is no tooltip).
7.	Click on Update until the bar has a value greater than the original.
8.	Note that hovering over the bar allows the initial bar to still be seen.
9.	Further clicks on Clear just show the original set of values, i.e. these are stuck in the UI.

Further notes:
•	The issue is seen when using the ‘DateTimePoint’ value type; if the values are ‘double’s, the issue is not seen.  (Note: The solution includes a conditional debug symbol ‘USEDOUBLES’, which allows the value type to be switched easily for testing.)
•	The issue is not seen with a line graph (LineSeries rather than ColumnSeries/StackedColumnSeries data).
•	The issue also appears on Android.

The demo solution is at: https://github.com/ianmichaelbrown/LiveChartsBarsBugDemo

**Comment by kshfire** [comment] 2023-10-05 05:10
First of all, thanks you for your interest.
Unfortunately, I can't share my codes here, but I attached a screen shot of the issue.
As I mentioned before, (version: beta 911)
  - Two sensors
  - data samples per a sensor: about 1000
  - sensor's measured data are replaced by the Button click
     * Clear ObservableCollection<ObservablePoint>
     * Add selected sensor's measured data to it
     * Then, automatically display it on the UI
  - Using ObservableCollection<ISeries> with 3 ScatterSeries and 1 LineSeries
     * But, afterimage issues are related to the ScatterSeries

Unlike the LinesSeries, the ScatterSeries sometimes has an issue where the previous graph remains.
  - In fact, I replace the ScatterSeries with LineSeries due to this problem.

I hope the attached image will help you solve the problem.


![image](https://github.com/beto-rodriguez/LiveCharts2/assets/17819458/f5b6ed60-46a9-4f45-8b94-3cb808ce8fbf)

**Comment by dlange-h3ko** [comment] 2024-10-16 07:30
I have a similar issue for a general reload of the Series. 

If I am using for example a LineSeries (also happening on others too, but not all). If I am creating the series navigating to a detailpage where I can add more entries and navigating back, the Series (and also Axis) will be cleared and added again (for maximum and minimum changes). 
In that case the graphs remains empty and are not redraw again in the UI.
This is not happening, when using CandlesticksSeries or CandlesticksSeries. BUT in that case the Stroke is not shown anymore. 
Maybe this is related to the same issue you are having.

Here the screenshot for the issue
correct:
<img width="467" alt="image" src="https://github.com/user-attachments/assets/37276be7-a2f6-4877-9fd5-deb47bfba6f5">
<img width="460" alt="image" src="https://github.com/user-attachments/assets/552c3be3-6c77-4c44-88d4-50eaa5e7f95f">

Incorrect after the reload (clear and add with an Observable Collection, as described in the documentation)
<img width="464" alt="image" src="https://github.com/user-attachments/assets/4bed1579-d5a7-456a-821c-fc017d1a91d1">
<img width="467" alt="image" src="https://github.com/user-attachments/assets/2651cd43-2b45-4e51-8cc1-781d057c11ab">

**Comment by beto-rodriguez** [comment] 2024-10-17 01:13
Sorry about the delay, @ianmichaelbrown that is the issue, thanks for the repo, I verified the issue.

It seems that when the `IsVisible` property changes, it disposes the ObservableCollection and updates are lost!

**Comment by ianmichaelbrown** [comment] 2024-10-17 08:18
> Sorry about the delay, @ianmichaelbrown that is the issue, thanks for the repo, I verified the issue.
> 
> It seems that when the `IsVisible` property changes, it disposes the `ObservableCollection` and updates are lost!

No problem, hope I was some help to you. :-)

**Comment by beto-rodriguez** [comment] 2024-10-19 20:23
This is now fixed with the referenced PR.

It will be included in the next version of the library, thanks for the report!!

**Comment by ianmichaelbrown** [comment] 2024-10-21 08:17
@beto-rodriguez Thanks for fixing this.

**Closed** 2024-10-24 20:37 UTC
Labels: bug, requires more research, priority 1

**Comment by Daimonion1980** [comment] 2024-10-28 13:37
Thanks for your effort

For case #1505 I tested the latest changes from dev branch with my [Demo App](https://github.com/Daimonion1980/livechartsDemo) but the last graph does not disappear. (Code is updated in repo and the solution accepts the livecharts solution in a folder next to the own solution folder)

![Zwischenablagebild (5)](https://github.com/user-attachments/assets/52cc9fcc-0845-4c0e-8b9f-567b2319740e)

I also tested 2.0.0-rc4.5 prerelease with same result. (Not uploaded in github repo)

**Comment by beto-rodriguez** [comment] 2024-10-28 17:54
@Daimonion1980 that seems a different problem, I added more details on your repo (thanks for sharing it!)

https://github.com/Daimonion1980/livechartsDemo/pull/1
