### ISSUE TITLE
DataFactory.Fetch()'s InvalidOperationException with collection while mouse clicking (potential race-condition at nearest code)

### ISSUE THREAD

**Issue by Malstraem** [beto-rodriguez/LiveCharts2#533] opened 2022-06-19 18:31 UTC
**Describe the bug**
@beto-rodriguez, hi, thanks for great chart library,

my team developing a highly loaded model, a new value can get into the series very quickly, sometimes the interval can be about 1 millisecond or even less. I used sync because the collection is being updated from a different thread. However, the application could suddenly crash. I sat with the debug for a while and found out that the problem is probably in the click on the chart (or rather what follows it, unfortunately I don't have much time now to figure out where exactly the cause of the problem is).

After writing a minimal example to reproduce, I saw issues #383, #225 and yes, you can get an exception in your multithreading viewmodels.

![image](https://user-images.githubusercontent.com/59914970/174494947-6d9e3315-438d-4566-b899-0682bdfa4e9a.png)
![image](https://user-images.githubusercontent.com/59914970/174494581-c21716f7-7ea5-444f-b5a7-d3b3bac8a734.png)

I thought the problem is ZoomMode specific, but when it is enabled, there is just a higher chance of getting an exception.

**To Reproduce**
Just click a lot :)

**Additional context**
I think we should open a discussion to solve this problem as soon as possible, literally any mouse click on the chart can cause the application to crash, the problem is not only for those who update the series very quickly. I will also try to explore the source code in more detail and help in solving.

**Comment by beto-rodriguez** [comment] 2022-06-19 21:37
Hi and thanks for the issue, this seems to be a threading issue.

When updates come from multiple threads, you need to sync your changes with the plot, take a look at the following solution:

https://github.com/beto-rodriguez/LiveCharts2/issues/225#issuecomment-1012488255

**Comment by beto-rodriguez** [comment] 2022-06-19 23:10
Hi and thanks for the issue.

Did you try https://github.com/beto-rodriguez/LiveCharts2/issues/225#issuecomment-1012488255?

Normally this happens because the data changes in another thread while the charts is being measured.

**Comment by Malstraem** [comment] 2022-06-20 06:31
@beto-rodriguez, i checked the multithreading viewmodels again and

>After writing a minimal example to reproduce, I saw issues https://github.com/beto-rodriguez/LiveCharts2/issues/383, https://github.com/beto-rodriguez/LiveCharts2/issues/225 and yes, you can get an exception in your multithreading viewmodels.

this is not true - second viewmodel with uiWorker is thread-safe, no exceptions. **With the first viewmodel, we expect this to be thread safe, but this is not the case and it has race-condition and exception.**
 
I will use ui thread invoker for the first time, but I think this is not the way that the user expects - **no exceptions should be thrown if the collection is correctly locked** (my code or your first viewmodel).

Need to find a place that creates a race-condition.

**Comment by beto-rodriguez** [comment] 2022-07-14 03:21
I will close this issue for now since it seems that this issue does not belong to the library. I have tested this and I am not able to reproduce the issue, please ensure to follow any of the alternatives mentioned, feel free to reopen this issue or a new one if you find any relevant information, thanks again for the issue :)

**Closed by beto-rodriguez** 2022-07-14 03:21 UTC

**Comment by Malstraem** [comment] 2022-07-14 06:24
> I will close this issue for now since it seems that this issue does not belong to the library.

Exception still thrown in the first multithreading viewmodel :)

![image](https://user-images.githubusercontent.com/59914970/178913396-c148bee6-5637-445a-b643-393284e89aa9.png)

> I have tested this and I am not able to reproduce the issue

Try to use any macro recorder for fast mouse clicking, since this is a race condition, either the 1 or 1001 click can lead to a crash.

I still intend to deal with the problem as free time appears, but I hope that you will reproduce the problem and agree with its existence.

**Comment by beto-rodriguez** [comment] 2022-07-14 06:43
I will keep an eye on this, it is just not reproducible from my side, I will try to emulate the multiple clicks to get this issue.

internally when you click on the chart, the library fires an update, and the library calls the update on the UI thread (or should), if your data update also happens in the UI thread then you should not get this exception.

As a workaround in your case, you can try to disable the tooltips, so the library ignores the pointer events and the chart is not refreshed on click.
