### ISSUE TITLE
Access % share of points in pie chart labels 

### ISSUE THREAD

**Issue by korneliuscode** [beto-rodriguez/LiveCharts2#520] opened 2022-06-09 19:22 UTC
In LiveCharts v1 I could access the share of a value in the piechart through the ``Participation`` attribute in the formatter function. 
I could not find an equivalent in v2 yet. It would be great to add this again to show the % AND the absolute values as well as decide to not show the labels on a pie chart if the share is under a specific %.

This is an example of what worked in v1:
`Func<ChartPoint, string> labelPoint = chartPoint =>  chartPoint.Participation > 0.03 ? string.Format("{0:N} ({1:P}), {2}", chartPoint.Y, chartPoint.Participation, chartPoint.SeriesView.Title) : "";`

**Comment by Dennis-Scheurer** [comment] 2022-06-21 14:58
I also think this would be a great addition!

**Comment by beto-rodriguez** [comment] 2022-07-14 04:02
Thanks, this was missing, it is now supported with the referenced commit and will be included in the next version of the library.

**Closed by beto-rodriguez** 2022-07-14 04:02 UTC

**Comment by korneliuscode** [comment] 2023-07-30 16:54
This is really great! Thanks a lot. I noticed that there is a NaN if there is only one value at a given point. As soon as there are 2, all the zeros show 0%.
![image](https://github.com/beto-rodriguez/LiveCharts2/assets/7031553/bdda95ea-02ca-4094-8684-ae29054776e8)

**Comment by beto-rodriguez** [comment] 2023-07-30 22:15
@korneliuscode I am sorry I can't reproduce; this works for me:

````c#
        var data = new[] { 6 };

        Series = data.AsPieSeries((value, series) =>
        {
            series.MaxOuterRadius = outer;
            outer -= 0.1;

            series.DataLabelsPaint = new SolidColorPaint(SKColors.White)
            {
                SKTypeface = SKTypeface.FromFamilyName("Arial", SKFontStyle.Bold)
            };

            series.DataLabelsFormatter =
                point =>
                {
                    var pv = point.Coordinate.PrimaryValue;
                    var sv = point.StackedValue!;

                    var a = $"{pv}/{sv.Total}{Environment.NewLine}{sv.Share:P2}";
                    return a;
                };
        });
```

![image](https://github.com/beto-rodriguez/LiveCharts2/assets/10853349/4b977fc1-4334-4316-aa87-be207cfa88bc)

What am I missing?

**Comment by korneliuscode** [comment] 2023-07-31 04:33
It’s a stacked bar chart and not every point has all the values. I could share some sample later.
