### ISSUE TITLE
Angular Gauge: Changing Needle Value prints seemingly random number (10 - 12) into the console.

### ISSUE THREAD

**Issue by nicolasfoehn** [beto-rodriguez/LiveCharts2#1411] opened 2023-12-22 01:13 UTC
**Describe the bug**
Everytime I change the value of my angular gauge needle in C# WPF (.net6) via Needle.Value = 10 (for example) the console prints a number. This clutters my console because I update the needle value quit frequently. The number doesn't seem to have any connection to the value I set the needle to.

**To Reproduce**
Implement an angular gauge and use Needle.Value = whatevernumber;
And console prints number.

**Expected behavior**
I don't excpect it to print anything.

**Comment by troygeiger** [comment] 2024-02-18 21:31
I am seeing the same with the Avalonia package. I think the messages are coming from the AngularTicksVisual where there is a Trace.WriteLine(_visuals.Count). I don't think the console messages are caused the this project though since I'm not seeing any ConsoleTraceListener being added to Trace.Listeners anywhere in this repo so that may be added by another unrelated package reference. Either way, it doesn't appear to be caused by this project.

I was able to work around it  by calling Trace.Listeners.Clear(); in my project. You also could look for the ConsoleTraceListener in the Trace.Listeners collection and then remove it if it exists.

**Comment by N4gl3r** [comment] 2024-04-09 13:10
Same issue: https://github.com/beto-rodriguez/LiveCharts2/issues/1370

**Comment by beto-rodriguez** [comment] 2024-09-15 18:48
Thanks for the report, we can track this at #1370, this will be fixed in the next version of the library.

**Closed by beto-rodriguez** 2024-09-15 18:48 UTC
