### ISSUE TITLE
MAUI: Chart not showing when using CollectionView with DataTemplate

### ISSUE THREAD

**Issue by vanillaFriday** [beto-rodriguez/LiveCharts2#1239] opened 2023-09-13 09:17 UTC
**Describe the bug**
When I try to use LiveCharts2 within a CollectionView and a DataTemplate in MAUI no chart is showing up (see SampleProject).

**To Reproduce**
1. Go to https://github.com/vanillaFriday/MauiAppTestCollViewLiveCharts2.git
2. Start program -> LiveCharts2 is loading correctly
3. Click on 'to CollectionView'
4. No chart is showing using the same DataBase

**Expected behavior**
Chart should be able to be wrapped in a DataTemplate to reuse it easily.

**Desktop:**
 - OS: Windows 11 with .NET7 MAUI Template
 - Target Framework 10.0.17763.0

<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:local="clr-namespace:MauiAppTestCollViewLiveCharts2"
             xmlns:lch="clr-namespace:LiveChartsCore.SkiaSharpView.Maui;assembly=LiveChartsCore.SkiaSharpView.Maui"
             x:DataType="local:ChartViewModel"
             x:Class="MauiAppTestCollViewLiveCharts2.NewPage1">

    <ContentPage.Content>
        <Grid>
            <CollectionView x:Name="collData"
                ItemsSource="{Binding Diagrams}">
                <CollectionView.ItemTemplate>
                    <DataTemplate>
                        <lch:CartesianChart Series="{Binding Series}"
                                            YAxes="{Binding YAxes}"
                                            Sections="{Binding Sections}">
                        </lch:CartesianChart>
                    </DataTemplate>
                </CollectionView.ItemTemplate>
            </CollectionView>
        </Grid>
    </ContentPage.Content>

</ContentPage>

**Comment by beto-rodriguez** [comment] 2023-10-31 22:22
Hello and thanks for the report.

The issue is not caused by the the DataTemplate, in your example set the HeightRequest="400" and WidthRequest="400" and you will see the chart.

I am cont completely sure if we must specify something for Maui so LiveCharts controls try to take all the available space, I will keep an eye on that, but that seems a different issue, I will close this since it seems solved.

**Closed by beto-rodriguez** 2023-10-31 22:22 UTC

**Comment by beto-rodriguez** [comment] 2024-10-18 14:06
@nk-alex glad it worked in debug.

I have faced similar issues in Maui, normally this happens when the types in the ViewModel and the View do not match.
