### ISSUE TITLE
Scroll Wheel Breaking

### ISSUE THREAD

**Issue by mcash95** [beto-rodriguez/LiveCharts2#1313] opened 2023-10-17 20:50 UTC
When using scroll wheel on a PieChart throws an Unable to cast error.

_Unable to cast object of type 'LiveChartsCore.PieChart`1[LiveChartsCore.SkiaSharpView.Drawing.SkiaSharpDrawingContext]' to type 'LiveChartsCore.CartesianChart`1[LiveChartsCore.SkiaSharpView.Drawing.SkiaSharpDrawingContext]'._

What is the scroll wheel attempting to accomplish?

Thank you in advance! Love the functionality you have provided

**Comment by beto-rodriguez** [comment] 2023-10-18 03:31
Please update to rc1.2 the issue is gone there.

**Comment by beto-rodriguez** [comment] 2023-10-18 16:49
duplicate of #1265

**Closed by beto-rodriguez** 2023-10-18 16:49 UTC
