### ISSUE TITLE
How to properly display timeseries data

### ISSUE THREAD

**Issue by MariaCobretti** [beto-rodriguez/LiveCharts2#959] opened 2023-03-16 18:49 UTC
I have a data series that goes like this..
(I ommited some points as well as the values)

10.03.2023 16:48:00
11.03.2023 19:12:00
13.03.2023 00:00:00
14.03.2023 02:24:00
15.03.2023 09:36:00
16.03.2023 00:00:00

how can i display them using axis Lablers (or another idea)

best i could manage was this..

![image](https://user-images.githubusercontent.com/17946690/225722640-accc71a8-2fa8-4d14-ab5c-9d69f7ac27b6.png)

main thing i want is not to display a paint at 1203.2023 since that one is missing in the series.
also nice would be to center the labels more properly, or remove the last label

thanks

**Comment by Albert634515** [comment] 2023-03-21 16:34
I have my axis like this:
var xaxes = new List<Axis>
            {
                new Axis
                {
                    Labeler = value => new DateTime((long) value).ToString("dd/MM/yyyy"),
                    LabelsRotation = 15,
                    Position = AxisPosition.Start,
                    MinStep = TimeSpan.FromDays(1).Ticks,
                    UnitWidth = TimeSpan.FromDays(1).Ticks
                }
            };

Does this help you?

**Comment by MariaCobretti** [comment] 2023-03-21 19:04
this would still draw the point at 3/12/2023 even though there is no data

**Comment by Albert634515** [comment] 2023-03-25 13:04
You always add the point to the data selection, but set that value of that data point to null, then it should not be drawn in the graph

**Comment by MariaCobretti** [comment] 2023-03-27 09:09
thats not true

**Comment by beto-rodriguez** [comment] 2023-07-30 22:38
Did you try adding a `null` point? 

https://lvcharts.com/docs/WPF/2.0.0-beta.850/samples.general.nullPoints

I will close this for now, since that should be enough, but feel free to reply or create a new issue if that does not work as intended.

**Closed by beto-rodriguez** 2023-07-30 22:38 UTC
Labels: documentation, question
