### ISSUE TITLE
Performance plummets and UI freezes when data value flips signs a lot

### ISSUE THREAD

**Issue by danielgruethling** [beto-rodriguez/LiveCharts2#1263] opened 2023-09-20 14:53 UTC
**Describe the bug**
When a value flips between two values very fast (e.g. flips signs, or jittering) the performance of the chart plummets until the UI completely freezes.
Even though the same amount of points is contained in the series the performance varies extremely depending on the distance between two values on the y-axis.

**To Reproduce**

1. Clone the LiveCharts2 repo commit 5150cd3ff03e6585cc30e100d786f2d7d9b08847
2. Change line 79 in ViewModelsSamples/General/MultiThreading2/ViewModel.cs to `s_current *= -1;`
3. Start the WinUISample
4. Open the MultiThreading2 example
5. Observe UI performance being very poor until it freezes

**Expected behavior**
UI performance does not plummet and is as smooth as it is in the example without this change.

**Screenshots**
Ui is frozen here:
![grafik](https://github.com/beto-rodriguez/LiveCharts2/assets/31628469/b5b6968d-ef46-4c39-aa92-a238bba200e1)

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser: N/A
 - Version: git commit 5150cd3ff03e6585cc30e100d786f2d7d9b08847

**Smartphone (please complete the following information):**
 - Device: N/A
 - OS: N/A
 - Browser: N/A
 - Version: N/A

**Additional context**
In my app some measurements jitter quite a bit and this affects performance of the UI thread. So much even that I can freeze my whole UI if I display enough points.

**Comment by beto-rodriguez** [comment] 2023-10-31 21:37
Hello and thanks for the issue.

The thig here is that you are drawing an extremely long path, this is the result I get:

![heat](https://github.com/beto-rodriguez/LiveCharts2/assets/10853349/cb746a72-b2ad-446b-98fd-c7d8abd220b2)

But in my case, all that blue color is not a fill, it is an extremely long stroke that looks like a fill, that is inefficient, but I do not think that that issue belongs to LiveCharts, you will also face that performance when drawing a long path like this one with SkiaSharp.

The library will offer a high-performance package, that is basically a structure that virtualizes the points in the UI, that issue will not happen with the high-performance package.

I will close this for now since this should be already covered (when the high-performance package is released), and that performance impact is not caused by LiveCharts  but by the length of the path.

**Closed by beto-rodriguez** 2023-10-31 21:37 UTC
Labels: not a bug

**Comment by danielgruethling** [comment] 2024-10-02 07:05
So it has been a year now but the high-performance package is nowhere in sight and this problem is still happening.

Meanwhile I have been testing if this problem happens in ScottPlot5 which also uses Skiasharp but the problem does not happen there when using the SignalXY series which would be the equivalent to the series used in the sample above. But Scottplott5 is not compatible with .NET6, other dependencies lock me on .NET6 and this is the best chart library I could find for .NET6.

Is there any chance this problem would be addressed?

**Comment by beto-rodriguez** [comment] 2024-10-02 07:11
The main difference with Scott plot is that livecharts is animated, also  I think that library uses a virtualization algorithm (it's  a reason why it runs faster) have you tried disabling animations?

**Comment by danielgruethling** [comment] 2024-10-02 07:27
Disabling animations is setting the EasingFunction to null correct? I do that and the UI still freezes. I have some oscillating sensor data which updates at a rate of 10 values every millisecond. But even when I compress 100 values into one so I only have 10 values every 100 milliseconds, which is when I update the chart with new data, it still freezes.

This is an example of the data:
![grafik](https://github.com/user-attachments/assets/7392ed33-e4f4-4b51-96d5-55a3d048037a)

**Comment by beto-rodriguez** [comment] 2024-10-02 07:55
> Disabling animations is setting the EasingFunction to null correct?

Yes, with this setting the chart will be drawn in just one frame (instead of 60 times per second)

About the issue you are facing, it seems that something else might be locking the UI thread, take a look at the sample provided in this repo, especially here:

https://github.com/beto-rodriguez/LiveCharts2/blob/master/samples/ViewModelsSamples/General/MultiThreading/ViewModel.cs#L46

The default sample, adds 1 point per millisecond on 10 different tasks, that is a similar case to yours, and thigs are super smooth, actually in the next gift, I modified the `readTask` to 100, and things are really smooth (even with animations):

![anim](https://github.com/user-attachments/assets/41fc2e4d-cea1-42f7-888b-fb779268dc69)

Notice the issue you reported initially, is completely different to this one, in your current issue I think that something else in your side is freezing the UI thread.

**Comment by danielgruethling** [comment] 2024-10-02 08:48
> Notice the issue you reported initially, is completely different to this one, in your current issue I think that something else in your side is freezing the UI thread.

I was looking for a minimal reproduction without actually giving out my code and the sample had the update rate I wanted but wasn't oscillating so I did the `s_current *= -1;` to kind of simulate that.
The only other thing that is interfering with the UI thread would be a few number boxes displaying the most recent values. They are filtered to only show every other value like the compressed values in the graph and using a threshold algorithm so only one call on the UI thread is made until the value is actually updated though.

I do buffer all the chart values in a seperate collection and add them in 100ms intervalls to the chart collection while I remove the same amount from the front of the chart collection.

I'll see what happens if I only try to update the chart. Maybe there is an issue with my filtering or threshold algorithm but it all works without problems when I use scotplott which led me to believe that the chart would be the issue.

**Comment by beto-rodriguez** [comment] 2024-10-02 09:09
> it all works without problems when I use scotplott which led me to believe that the chart would be the issue

It looks like LiveCharts is slower, I think that is expected since this library has the overhead of animations, but anyways, the performance you are getting seems slower than usual.

**Comment by danielgruethling** [comment] 2024-10-02 09:58
I am not sure how this works so smoothly on your machine. I changed line 79 to `s_current = _r.Next(-10, 10);` now so it will actually oscillate randomly between -10 and 10 and this happens:

![ezgif-4-8bef16ed35](https://github.com/user-attachments/assets/f7d10a38-e4c7-4947-8406-4585b62cb5cf)

I switched to the current commit for rc3.3 to make sure this happens on the most current version as well.

**Comment by beto-rodriguez** [comment] 2024-10-02 12:46
Please ensure that you are only running that sample once, as the note says, it has a memory leak and its just for demonstration purposes.

**Comment by beto-rodriguez** [comment] 2024-10-02 12:49
For me that sample runs supper smoothly

![image](https://github.com/user-attachments/assets/55458457-6062-4878-87fe-5049fd56b301)

**Comment by danielgruethling** [comment] 2024-10-02 13:33
I am only running it once and getting the same result. I do see a lot more processor usage though. Probably due to no dedicated graphics card being present.
![grafik](https://github.com/user-attachments/assets/2aa9c385-85d2-4eed-9d5b-ad2e9de85e55)
