### ISSUE TITLE
Not all points shown in ScatterSeries until clicked anywhere

### ISSUE THREAD

**Issue by HubertK2002** [beto-rodriguez/LiveCharts2#1421] opened 2024-01-11 13:46 UTC
I have ISeries array. Fourth element is ScatterSeries with Type ErrorTimePoint extending DateTimePoint
```
public class ErrorTimePoint : DateTimePoint
    {
        public string Desc { get; set; }
        public ErrorTimePoint(DateTime time, double value, string desc) : base(time, value)
        {
            Desc = desc;
        }
    }
```
I have container with my data
```
private ObservableCollection<ErrorTimePoint> ErrorsFiltered { get; set; } = new();
```
and each time i change filters i set again ISeries[3] like that
```
Series[3] = new ScatterSeries<ErrorTimePoint>
            {
                Name = "Errors",
                GeometrySize = 13,
                Stroke = new SolidColorPaint(SKColors.Red, 2),
                Fill = FillPoints ? new SolidColorPaint(SKColors.Red, 2) : null,
                YToolTipLabelFormatter = (chartPoint) => $"{(chartPoint.Model ?? new ErrorTimePoint(new(), 0, "")).Desc}",
                Values = ErrorsFiltered
            };
```
There is problem that after a few changes I start to notice that some points disappear when they shouldn't. I wondered why. I checked and they are in ErrorsFiltered and then i noticed that sometimes they're back. And you know what? They are always there, but they are invisible. When I hover mouse at position where they should be I see tooltip with their value. And what is more strange when I click anywhere on the chart they're back.

![Zrzut ekranu 2024-01-11 144001](https://github.com/beto-rodriguez/LiveCharts2/assets/34602161/9a42649a-04ac-4300-88e8-60c1e71715c1)
[example video.zip](https://github.com/beto-rodriguez/LiveCharts2/files/13903923/example.video.zip)

Sometimes problem starts later
[example video 2.zip](https://github.com/beto-rodriguez/LiveCharts2/files/13904065/example.video.2.zip)

It only happens when first checked. When I do it again in the same start it works fine. But if I check checkboxes not checked before shit happens again.
[example video 3.zip](https://github.com/beto-rodriguez/LiveCharts2/files/13904151/example.video.3.zip)

**Comment by HubertK2002** [comment] 2024-01-21 14:48
Moreover there is another. Data are showed on the chart even if they aren't in series values. They are for sure reloaded because tooltip isn't showed. But view isn't cleared. When i check/uncheck Iradion orange dots should be removed from chart.

[Uploading bug2.zip…]()

**Comment by beto-rodriguez** [comment] 2024-10-22 22:53
Hello

I will close this for now for 2 reasons.

1. The next version of the library includes https://github.com/beto-rodriguez/LiveCharts2/pull/1656, this should fix your issue.
2. I wish I could test your case, to confirm that the issue is fixed, but I would need a repo or zip where I can see the issue and try with the latest library.

Please when rc-4 is release, try to update, if the issue persists let me know and I will take a look again, a small project with the case would have been useful to fully confirm that the issue is gone.

**Closed by beto-rodriguez** 2024-10-22 22:53 UTC
Labels: requires-attention
