### ISSUE TITLE
Crosshairs on two charts

### ISSUE THREAD

**Issue by alexachso** [beto-rodriguez/LiveCharts2#739] opened 2022-11-09 20:16 UTC
**Describe the bug**
I will start by describing a little bit my setup. I have 2 charts in a tab control. Each chart is in a different tab. For both Charts, I have binded the XAxis and YAxis to the same objects as so,
![image](https://user-images.githubusercontent.com/12586000/200928461-7e0c6724-54c4-42f3-b2f3-b4bca32a9b4c.png)

Thus, If I change some property for the XAxis, the modification should reflect on both charts, because they are binded to the same property.

I have created a button in order to enable or disable the crosshair feature for the axis. I do this like so, 
![image](https://user-images.githubusercontent.com/12586000/200929271-dfe70788-6d12-4851-883f-f29c8b2dae03.png)

If I run the application, the button works fine and the crosshairs will be enabled or disabled, but ONLY for the chart that was rendered when I click for the first time on the button (to enable the crosshairs). So, let's say we open the application and open tab 2 "chart 2". We click on the button in the bottom right of the application and the crosshairs will appear on chart2. If we let the crosshairs enabled and navigate to tab 1 "chart 1" the crosshairs will not appear even tho they are "enabled". We could now re-click on the button in order to disable the crosshairs. We then navigate back to the "chart 2" tab and sure enough, the crosshairs are not present because we disabled them. If we then re-click on the button to re-enable the crosshairs, sure enough, the crosshairs reappear on the chart. 

Another problem I've seen is that the label of the crosshair for the X-axis is behind the axis, so it is not visible to the user.

**To Reproduce**
Run this simple project, everything is in place to play with it and see for yourself.
[SimpleChartProject.zip](https://github.com/beto-rodriguez/LiveCharts2/files/9974771/SimpleChartProject.zip)

**Expected behavior**
I was expecting to see the crosshairs (when "enabled") on both charts. 
I was also expecting to see the label of the crosshair on the X-Axis.

**Screenshots**
![image](https://user-images.githubusercontent.com/12586000/200932607-8fde43ab-1914-42e9-aa51-091f99d01cb1.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - WPF application
 - Version of the livecharts2 is 2.0.0-beta.516

**Comment by alexachso** [comment] 2022-11-28 13:22
Update with livecharts2 is 2.0.0-beta.601:

Crosshairs seem to work better. Once the crosshairs activate with the button, when we switch tabs the crosshairs now appear on both charts as expected 👍.

But, the problem of the label of the crosshair for the X-axis behind the axis is still present.
Here is the project updated with beta.601 to fiddle with -> [SimpleChartProject.zip](https://github.com/beto-rodriguez/LiveCharts2/files/10104050/SimpleChartProject.zip) .

PS: Ideas for improvement: 
1 - Could be nice to control the size of the text inside the crosshair label (property). The default value seems kind of too big. 
2 - We could have a property to enable or disable the crosshair (to display it or not).

**Comment by beto-rodriguez** [comment] 2022-12-16 19:28
Thanks for the sample, I was playing with your project, the issue here is that you are using the same `Paint` instance for both axes, this is a limitation, and you need a new instance for each axis.

Instead of:

```c#
XAxes = new[] { new Axis { CrosshairPaint = _crosshairPaint }};
YAxes = new[] { new Axis { CrosshairPaint = _crosshairPaint }};
```

Do:

```c#
XAxes = new[] { new Axis { CrosshairPaint = new SolidColorPaint(SKColors.Black)}};
YAxes = new[] { new Axis { CrosshairPaint = new SolidColorPaint(SKColors.Black)}};
```

This is caused because each axis sets a different clipping rectangle:
https://github.com/beto-rodriguez/LiveCharts2/blob/master/src/LiveChartsCore/Axis.cs#L681
https://github.com/beto-rodriguez/LiveCharts2/blob/master/src/LiveChartsCore/Axis.cs#L688

The issue will be gone when you use a new instance for each series, I think this is a necessary limitation, I will think possible solutions to prevent this, but for now a unique instance for each axis is necessary.

**Comment by beto-rodriguez** [comment] 2022-12-18 19:48
I will close this for now since this seems a limitation by design, all we can do here is add this note to the notes.

**Closed by beto-rodriguez** 2022-12-18 19:48 UTC
Labels: has workaround
