### ISSUE TITLE
Inefficient performance due to GC pressure

### ISSUE THREAD

**Issue by daltzctr** [beto-rodriguez/LiveCharts2#1083] opened 2023-06-23 14:32 UTC
In reviewing the code for another issue, I noticed a lot of object allocations that create heavy GC pressure (thus lowering performance at high rates/high quantities of data). Specifically, a ton of `SolidColorPaint` objects get created and then cleared.

I propose replacing the instantiation of `SolidColorPaint` with a ring-buffer implementation that will then feed it into the actual dataset that gets rendered on the chart. This will reduce/entirely eliminate GC pressure and in initial testing, greatly improve performance in real-time scenarios.

**Comment by daltzctr** [comment] 2023-06-23 18:53
Expanding this. Real time performance of even a small amount of data (100pts/250ms) is poor and causes a ~20-50ms lockup of the UI due to GCs caused by `Measure()` and `Invalidate`

**Comment by beto-rodriguez** [comment] 2023-06-23 19:17
Hi and thanks for the report.

Can you please provide an example with this case?

**Comment by beto-rodriguez** [comment] 2023-07-05 16:20
After some research I was able to reproduce the issue, in my case I added and removed 1,000 points every 100ms and that caused the GC to run quite often.

#### Case 1 ([code here](https://gist.github.com/beto-rodriguez/960209adfacf3360094a0c7ba27a91b6))

I am using an object that implements [IChartEntity](https://lvcharts.com/api/2.0.0-beta.800/LiveChartsCore.Kernel.IChartEntity), 
This interface is also implemented by all the default objects provided in the library (like `ObservableValue` or `ObservablePoint`), by default the `Measurement` class holds a reference to the visual drawn in the UI, this is used internally to track and animate things in the library, that is the main reason that forces the GB to run that often, because when we are removing a point in the chart then the GC also needs to remove the visual in the UI.

![gc1](https://github.com/beto-rodriguez/LiveCharts2/assets/10853349/759f740c-1b3e-4f97-9483-6ef70f3d0df3)

#### Case 2 ([code here](https://gist.github.com/beto-rodriguez/e6b000eda0978172da2aa26e32941b06))

In a case like this, we can re-use the same visual in the UI, a quick way of doing so, is to use a mapper and use the index of the element in the array to map the visual with the data, now we are just updating the old visual in the UI instead of delete/create a new one:

![gc2](https://github.com/beto-rodriguez/LiveCharts2/assets/10853349/1e569ccc-e6ba-42d5-a451-e94f8bdb7b79)

### Conclusion

We can also help LiveCharts to improve things, this needs better docs, and I will consider this case when I build the examples/docs of the high-performance package, In general I am not disappointed with the default behavior of the library, because it allows us to create plots like [this](https://raw.githubusercontent.com/beto-rodriguez/LiveCharts2/dev/docs/samples/bars/race/result.gif), that case is not possible using the Case 2 approach, then when we have cases where we need to change big amounts of data in short periods of time, we can help the library to manage that case.

I will close this for now because it seems that we can help the GC in special cases like this, I hope I made sense, but please feel free to reply or create a new issue if my alternative is not enough in your case (I will build an article about this when I create the high-performance tips).

**Closed by beto-rodriguez** 2023-07-05 16:20 UTC

**Comment by daltzctr** [comment] 2023-07-20 23:18
@beto-rodriguez can you give a more complete implementation of case 2? I don't see any logic related to mappers or changing positions.

**Comment by daltzctr** [comment] 2023-08-01 19:52
Just wanted to give a bump on this. Manually applying a `Labeler = (value) => {}` somewhat works, but when there are multiple series, their values don't actually line up with the X axis.

Basically, how do we plot multiple rolling (updating from live data) series without incurring heavy GC penalties (which negatively effect application usage)?

**Comment by beto-rodriguez** [comment] 2023-08-01 19:54
@daltzctr I will add an example to the repo/site soon.

**Comment by beto-rodriguez** [comment] 2023-08-03 15:49
I think this is also fixed now with #1151, here is a chart that adds 50 points each millisecond, GC seems decent now!

![v](https://github.com/beto-rodriguez/LiveCharts2/assets/10853349/ad85804d-8f45-43a6-8d29-c583439d5af1)

The issues in #1151 we caused by tooltips and legends, the `RelativePanel` class was not disposing the background color (755f86c101a024d7f4f415811cab09be8655531d), also the legend was measured every time the chart was updated, legends use the `RelativePanel` class, now legends are not calculated always (036e10b77d033977dc4ccf5a133afa5cf20a15f1), it seems that now everything is smooth, thanks for the report!

**Comment by daltzctr** [comment] 2023-08-03 15:51
Epic!

**Comment by daltzctr** [comment] 2023-08-03 16:36
While this certainly improves the situation (nice!), the approach mentioned previously is still my preferred implementation. 

Without reusing coordinate points, and with about ~5 line series (each with 50 point updates every 75ms) and a few seconds of updates the chart gets "behind" on renders. This causes a situation where the GC pressure increases until the application eventually deadlocks. Reusing the coordinate pretty much solves this situation but introduces a few behaviors that have to be worked around.

When reusing points, I have observed:
- XAxis values no longer are correct, a custom XAxis mapper partially solves this
- When using a custom XAxis mapper (maybe this is my implementation), X values of points are no longer synchronized. The time delta's between each time is inconsistent (probably my implementation, but this is difficult to solve)
- Tooltips are overflowing (this might just be a general MAUI on desktop problem) when you have large series names ("Mylineseriesblahblah" and "mylineseries" shows this overflow of the tooltip container)

I have seen similar plot libraries implement an internal buffer (ring buffer) of points that the library will reuse. That was my suggested implementation in the original post in this thread. Reassigning the coordinate accomplishes a similar behavior, but skips lots of code that the library assumes (this is an assumption, not proven of mine).

To be clear, this project is absolutely amazing and you are an insane individual for maintaining a project whose scope is this large (and for free!). I, and I'm sure many others thank you for your work!

**Comment by beto-rodriguez** [comment] 2023-08-03 16:56
Just for the record, how many points does your series have?

**Comment by daltzctr** [comment] 2023-08-03 17:02
A maximum of 150 pointers per series. For context, I don't really expect amazing performance, just usable performance with up to ~6 series. 

So my series has 6 * 150 points with old points being "removed" and "new ones" being added every 75ms.

**Comment by daltzctr** [comment] 2023-08-03 17:56
MAUI/WinUI3.

**Comment by beto-rodriguez** [comment] 2023-08-03 18:10
The delay issue could also be related to how the library works, this is just a hypothesis, I need to check this.

LiveCharts is not updated every time the data changes, it is updated once every interval (default is 50ms), this is controlled by the [UpdaterTrottler](https://lvcharts.com/docs/Maui/2.0.0-beta.900/Overview.Animations#updaterthrottler-property) property, reducing this property interval could inprove your case, there is also #1027, maybe we need a way to disable the throttler and just update on every call, but that would require more work from your side, since maybe you would require to remove the observable stuffs and just call a chart update every time you need it.

**Comment by daltzctr** [comment] 2023-08-04 14:24
Update on every call would be nice to at least be able to trace the problem more deterministically.

**Comment by daltzctr** [comment] 2023-08-09 19:13
After some further overnight testing I can produce these results

- The new update dramatically improves the experience, even without point reuse. 
- My specific problem is caused by several MAUI specific bugs. Specifically, MAUI Frame has issues leaking memory whenever it's content changes. Replacing the usage of Frame with Border solves this.
- There is still some GC pressure when a tooltip is displayed, by I'm not sure much can be done about that.

Thaaaaaaaaaaaaaaaaankkkkkkkkkkkkkkkk youuuuuuuuuuuuuuuuuuuuu :D
