### ISSUE TITLE
GetImage() Stoped working for Boxplot in WPF in beta950

### ISSUE THREAD

**Issue by Zottel92** [beto-rodriguez/LiveCharts2#1251] opened 2023-09-18 15:24 UTC
**Describe the bug**
I found a bug after upgrading the library in my project.

The Feature of "getImage()" of SKCatesianChart fails after the upgrade to beta950 or rc1.

**To Reproduce**
1. Use beta920
2. Create a Image with the Code beneath (not to file but to a variable)
3. Do the same with beta950 or rc1 and it will fail.

**Expected behavior**
Since the code did not change and there is no wrong call of a method "getImage()" I would expect both versions of the library to work.

**Desktop (please complete the following information):**
 - OS: Win10

**Additional context**
```
            var boxPlotChart = new SKCartesianChart
            {
                Height = 50,
                Width = 130,
                DrawMargin = new LiveChartsCore.Measure.Margin(0),
                EasingFunction = null,
                XAxes = new Axis[] { new Axis() {
                    IsVisible = false, } },
                YAxes = new Axis[] { new Axis() {
                    ShowSeparatorLines = false,
                    IsVisible = false,
                    MinLimit = -0.001,
                    MaxLimit = 1.001,
                } },
                Series = ENTER-BOX-SERIES-LIST-HERE,
                LegendPosition = LiveChartsCore.Measure.LegendPosition.Hidden
            };


            var legendPic = boxPlotChart.GetImage();
```

**Comment by beto-rodriguez** [comment] 2023-09-24 19:07
Hello, what do you mean with fails? it seems to be working for me

**Comment by beto-rodriguez** [comment] 2023-10-18 18:09
I will close this for now, feel free to add more details so I can reproduce/fix.

**Closed by beto-rodriguez** 2023-10-18 18:09 UTC
Labels: more info required
