### ISSUE TITLE
Saving As Image Does Not Include Title

### ISSUE THREAD

**Issue by ajayre** [beto-rodriguez/LiveCharts2#708] opened 2022-10-24 05:25 UTC
Using this code to save the chart as an Image does not include the title the output:

```
var Ch = new SKCartesianChart(Chart);
var Img = Ch.GetImage();
...
Ch.SaveImage(ExportImageDialog.FileName, Format);
```

Andy

**Comment by beto-rodriguez** [comment] 2022-11-24 14:57
I am not able to reproduce this issue, what am I missing? notice this sample works: https://github.com/beto-rodriguez/LiveCharts2/blob/master/samples/ConsoleSample/ConsoleSample/Program.cs

**Comment by ajayre** [comment] 2022-11-25 06:03
I am changing the text at runtime - I don't see that in the example?

`            LabelVisual Title = (LabelVisual)Chart.Title;

            Title.Text = Settings.Title;
`

Andy

**Comment by ajayre** [comment] 2022-11-27 03:11
Even if I don't change the title at runtime it doesn't work. I am using WinForms. Here are sections of my code.

```
private LiveChartsCore.SkiaSharpView.WinForms.CartesianChart Chart;
```

```
            Chart.Series = Series;
            Chart.AnimationsSpeed = TimeSpan.FromMilliseconds(300);
            Chart.EasingFunction = null;
            Chart.Title = new LabelVisual
            {
                Text = "Simulation Data",
                TextSize = 18,
                Padding = new LiveChartsCore.Drawing.Padding(15),
                Paint = new SolidColorPaint(SKColors.Black)
            };
```

```
        /// <summary>
        /// Exports the chart as an image
        /// </summary>
        private void ExportImage
            (
            )
        {
            if (ExportImageDialog.ShowDialog() == DialogResult.OK)
            {
                var Ch = new SKCartesianChart(Chart);
                //Ch.Width = 1000;
                //Ch.Height = 300;
                var Img = Ch.GetImage();

                SKEncodedImageFormat Format = SKEncodedImageFormat.Png;
                string Ext = Path.GetExtension(ExportImageDialog.FileName);
                if (Ext == ".gif") Format = SKEncodedImageFormat.Gif;
                else if (Ext == ".bmp") Format = SKEncodedImageFormat.Bmp;
                else if (Ext == ".jpg") Format = SKEncodedImageFormat.Jpeg;
                else if (Ext == ".jpeg") Format = SKEncodedImageFormat.Jpeg;

                Ch.SaveImage(ExportImageDialog.FileName, Format);
            }
        }
```

Hopefully that will help you reproduce the problem.

**Comment by beto-rodriguez** [comment] 2022-12-16 15:26
Thanks! I finally was able to reproduce it!

**Comment by beto-rodriguez** [comment] 2022-12-16 15:33
That commit fixes this, this will be fixed since beta 700 (will publish soon)

**Closed by beto-rodriguez** 2022-12-16 15:33 UTC
