### ISSUE TITLE
Asynchronously Loading Series Breaks Line Chart Rendering

### ISSUE THREAD

**Issue by mark-monteiro** [beto-rodriguez/LiveCharts2#409] opened 2022-02-24 14:49 UTC
**Describe the bug**
I'm using WPF. Loading in series data asynchronously and then updating the chart via a binding update, breaks rendering.

**To Reproduce**
1. Bind the `Series` property on `CartesianChart` to a property in the view model that initialized to null
2. Asynchronously load the series data in the view model and then update the property for the `Series` binding
4. See error. The x-axis on the chart all gets squished to the far left and no data points appear on the chart

The following change to the view model reliably reproduces this error using the `Lines/Basic` sample in this repo:

```c#
public class ViewModel : INotifyPropertyChanged
{
    public ISeries[] Series { get; private set; }

    public event PropertyChangedEventHandler PropertyChanged;

    public Task Initialization { get; }

    public ViewModel()
    {
        Initialization = InitializeAsync();
    }

    private async Task InitializeAsync()
    {
        // fetch data
        await Task.Delay(1000);
        var data = new DateTimePoint[] {
                new DateTimePoint(DateTime.Parse("2022-02-18T14:32:13.3763080"),0.43000003695487976),
                new DateTimePoint(DateTime.Parse("2022-02-18T14:32:14.4189800"),0.4800000488758087),
                new DateTimePoint(DateTime.Parse("2022-02-18T14:32:15.4752700"),-0.320000022649765),
                new DateTimePoint(DateTime.Parse("2022-02-18T14:32:16.5301810"),-0.8700000643730164),
                new DateTimePoint(DateTime.Parse("2022-02-18T14:32:17.5877030"),-0.7400000691413879),
                new DateTimePoint(DateTime.Parse("2022-02-18T14:32:18.6422350"),-0.9500000476837158),
            };

        // Create series
        Series = new LineSeries<DateTimePoint>[] {
            new LineSeries<DateTimePoint> { Values = data }
        };
        PropertyChanged?.Invoke(this, new(nameof(Series)));
    }
}
```

**Expected behavior**
Chart should render normally.

**Screenshots**
![image](https://user-images.githubusercontent.com/2626103/155542660-7e8106a4-beef-4e20-ace0-82212b980632.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Platform: WPF
 - Version: replicated with current commit on master f76d585130469e122027e47be50d16d79003b8f1

**Additional context**
This pattern is useful because I don't want to show the chart at all until the data has been loaded. The code sample here doesn't include this, but I am using the Task in the `Initialization` property to show a "loading..." message in the UI while the data loads. 

Regardless, I need to be able to load the data asynchronously and have been unable to find a suitable workaround for this issue. This is the closest to a viable workaround I have been able to find. It's only the first render that is broken, adding additional points after the first broken render fixes the chart. Hopefully this also provides some insight into what the underlying issue is.

```c#
public class ViewModel
{
    public ISeries[] Series { get; }

    public Task Initialization { get; }

    private readonly ObservableCollection<DateTimePoint> _values = new();

    public ViewModel()
    {
        Series = new ISeries[]
        {
            new LineSeries<DateTimePoint> { Values = _values }
        };
        Initialization = InitializeAsync();
    }

    private async Task InitializeAsync()
    {
        // fetch data
        await Task.Delay(1000).ConfigureAwait(false);
        var data = new DateTimePoint[] {
            new DateTimePoint(DateTime.Parse("2022-02-18T14:32:13.3763080"),0.43000003695487976),
            new DateTimePoint(DateTime.Parse("2022-02-18T14:32:14.4189800"),0.4800000488758087),
            new DateTimePoint(DateTime.Parse("2022-02-18T14:32:15.4752700"),-0.320000022649765),
            new DateTimePoint(DateTime.Parse("2022-02-18T14:32:16.5301810"),-0.8700000643730164),
            new DateTimePoint(DateTime.Parse("2022-02-18T14:32:17.5877030"),-0.7400000691413879),
            new DateTimePoint(DateTime.Parse("2022-02-18T14:32:18.6422350"),-0.9500000476837158),
        };

        // Add first data point; chart is rendered incorrectly
        _values.Add(data[0]);

        // Wait a bit; this delay has to be long enough for this workaround to work
        // (maybe the animations need to complete?)
        await Task.Delay(1000).ConfigureAwait(false);

        // Add remaining series values; points/axis are rendered correctly
        foreach (var point in data.Skip(1))
        {
            _values.Add(point);
        }
    }
}
```

I think this may also be related to this existing issue: https://github.com/beto-rodriguez/LiveCharts2/issues/346

**Comment by XamMattia83** [comment] 2022-03-28 12:42
Hello! i have the same issue with a LineSeries<DateTimePoint> on Xamarin.Forms platform.  
To workaround this i'm doing:

- 1) fetch / add all the data points
- 2) await Task.Delay(some delay long enough to render.....guessing animations time-dependent)
- 3) Auto Rescaling X min - max limits by setting MinLimit = null and MaxLimit = null

Obviously is not the ideal situation because you'll always have to add some delay to your task but it works.

**Comment by beto-rodriguez** [comment] 2022-04-26 03:06
Hi!

I tried your example and it works for me, was this fixed in a previous commit? am I missing something?

**Comment by beto-rodriguez** [comment] 2022-05-20 17:59
I am not able to reproduce this, I will close this for now due inactivity, feel free to open a new issue if it persists

**Closed by beto-rodriguez** 2022-05-20 17:59 UTC
Labels: possible bug [unconfirmed]
