### ISSUE TITLE
2.0.0-beta-6xx lengend language bug.

### ISSUE THREAD

**Issue by hukjin** [beto-rodriguez/LiveCharts2#815] opened 2022-12-12 06:56 UTC
until 5xx version display the "korean" language in the legend but after update the 6xx version that is not show the language.

![11](https://user-images.githubusercontent.com/38930530/206980475-66431eab-60f6-4e02-9133-048ccf5ec0ad.PNG)
![22](https://user-images.githubusercontent.com/38930530/206980478-fc55e38f-9a98-467c-ae57-9495f7f7c60d.PNG)
![33](https://user-images.githubusercontent.com/38930530/206980483-9e7e93de-8fed-4b80-8c56-8fe12e496b2f.PNG)
![44](https://user-images.githubusercontent.com/38930530/206980487-3bf950cf-6bc3-421e-914b-6301433001f2.PNG)

**Comment by AhmadKelany** [comment] 2022-12-12 10:39
I think the problem is in the legend's font,
previously you could solve this by setting the LegendFont property of the chart to a font that supports Korean..

Now the LegendFont (and also the TooltipFont) are not available.

**Comment by beto-rodriguez** [comment] 2022-12-19 00:26
I am closing this, please see #816 for more details.

**Closed by beto-rodriguez** 2022-12-19 00:26 UTC
