### ISSUE TITLE
Sharing An Axis no label

### ISSUE THREAD

**Issue by Gexon** [beto-rodriguez/LiveCharts2#555] opened 2022-07-21 09:13 UTC
Sharing An Axis the labels disappeared

in version 2.0.0-beta.101 everything is fine
and starting from the 2.0.0-beta.200 version labels are not displayed
![Screenshot_9](https://user-images.githubusercontent.com/3332087/180176977-9c149944-e73b-4482-90ad-3f3a0b02aebe.png)

Only those that were visible when loading are displayed.
If you move the graph, the labels that have gone beyond the limits will disappear forever. 
No new labels appear either.
(yandex translate)

**Comment by Gexon** [comment] 2022-08-02 07:14
setting the EasingFunction to Null solved the problem, but now there is no animation.
<lvc:CartesianChart
    EasingFunction="{x:Null}"> 
</lvc:CartesianChart>

**Comment by beto-rodriguez** [comment] 2022-08-20 01:23
It seems that this issue should be fixed with the referenced commit.

I am not completely sure, but this fixes a similar issue I had.

Please let me know if this works for you in version beta.360 or latter (not published on NuGet yet, but it will be soon)

**Comment by beto-rodriguez** [comment] 2022-09-01 18:29
I am unable to reproduce this issue, I will close this for now, let me know if the issue persists in the latest version of the library.

**Closed by beto-rodriguez** 2022-09-01 18:29 UTC
Labels: bug, waiting for reply
