### ISSUE TITLE
X-axis on line chart goes outside the container (WinForms)

### ISSUE THREAD

**Issue by UhaBach** [beto-rodriguez/LiveCharts2#968] opened 2023-03-26 15:59 UTC
Hello.
I recently decided to try this library and ran into the following problem: when creating a line graph through code, the x-axis goes outside the container.
![image](https://user-images.githubusercontent.com/84489349/227787062-11a62f89-1646-4276-9816-0bc175a4e886.png)

        private double[] rndWalk(int length, double step)
        {
            var rnd = new Random();
            var data = new double[length];
            data[0] = 0;
            for (int i = 1; i < length; i++)
            {
                data[i] = data[i - 1] + (step * rnd.Next(-4, 5));
            }
            return data;
        }

        private void CreateTestTab()
        {
            int length = 300;
            double step = 0.1;
            double x = 0;
            double xInc = 0.0000002;
            ObservableCollection<P> points = new ObservableCollection<P>();
            var data = rndWalk(length, step);
            for (int i = 0; i < length; i++)
            {
                points.Add(new P() { X = x, Y = data[i] });
                x += xInc;
            }
            var series = new ObservableCollection<ISeries>
            {
                new LineSeries<P>
                {
                    Values = points,
                    Mapping = (p, point) =>
                    {
                        point.PrimaryValue = p.Y;
                        point.SecondaryValue = p.X;
                    },
                    LineSmoothness = 0.25,
                    Fill = null,
                    Stroke = new SolidColorPaint(SKColors.Red) { StrokeThickness = 2 },
                    GeometryFill = null,
                    GeometryStroke = null
                }
            };
            var chart = new CartesianChart();
            chart.Series = series;
            chart.ZoomMode = LiveChartsCore.Measure.ZoomAndPanMode.X;
            var tab = new TabPage();
            tab.Controls.Add(chart);
            chart.Anchor = AnchorStyles.Top
                            | AnchorStyles.Bottom
                            | AnchorStyles.Left
                            | AnchorStyles.Right;
            ChartTabControl.TabPages.Add(tab);
        }

**Comment by CMOSLouis** [comment] 2023-03-26 18:43
See about this issue that I commited. I think that it can solve your problem.

Url: https://github.com/beto-rodriguez/LiveCharts2/issues/960

**Comment by CMOSLouis** [comment] 2023-03-27 18:22
Your problem is easy to solve. You must instantiate an XAxe property and set the desired threshold. Here's my example:

`
 public List<ICartesianAxis> XAxes { get; set; }

XAxes = GetPropertiesXAxes().ToList();

public ObservableCollection<ICartesianAxis> GetPropertiesXAxes()
        {
            return new ObservableCollection<ICartesianAxis>
            {
                new Axis
                {
                    MinStep = 10.0,
                    ForceStepToMin = true,

                    Padding = new LiveChartsCore.Drawing.Padding(0, 0, 0, 12),
                    TextSize = 14,

                    ShowSeparatorLines = true,
                    SeparatorsPaint = new SolidColorPaint
                    {
                        StrokeThickness = 1,
                        IsAntialias = true,
                    },

                    Labeler = (value) =>
                    {

                        long posX = (long)value;

                        if(posX % 10.0== 0)
                        {
                         return $"{posX/10.0}";
                        }
                        return $"";
                    },
                },
            };
        }
`

**Comment by beto-rodriguez** [comment] 2023-06-08 18:19
Hello and thanks for the issue.

I am not able to reproduce this, can you please provide a project with the issue?

**Comment by beto-rodriguez** [comment] 2023-06-28 01:09
I will close this because we need more info to track this. feel free to reply here or open a new issue if you found more info about this case.

**Closed by beto-rodriguez** 2023-06-28 01:09 UTC
Labels: more info required, not verified
