### ISSUE TITLE
Share crosshair in multiple charts

### ISSUE THREAD

**Issue by MithrilMan** [beto-rodriguez/LiveCharts2#876] opened 2023-01-07 10:45 UTC
Using Blazor beta-700
I've 3 different charts with shared xAxis and I want to have shared crosshair too,
I've recorded the screen to show what's not consistent (3.5mb gif)
![chart-issue](https://user-images.githubusercontent.com/5107375/211145820-79676d5f-3619-4e5c-8654-4014b1ae846c.gif)

Now let me summarize what's not working explaining what's recorded on video:
- as soon as charts are displayed, crosshair is shown only on the chart instance I'm hovering with the mouse
- when I hover other charts it shows but it's not aligned, each one has its own position
- as soon as I start pan the chart, all crosshair start to synchronize (**this is what I'm trying to achieve constantly**)
- while the animation is still playing, moving the mouse without panning (so without pressing any button) still keep crosshair in sync
- as soon as the chart animation stops, crosshair stop being in sync

**Comment by beto-rodriguez** [comment] 2023-07-10 19:54
This is by design, currently the crosshair is by chart, there are no shared crosshairs, this is actually a new feature, and it seems interesting.

**Comment by beto-rodriguez** [comment] 2024-10-14 18:26
Fixed with the referenced commit and will be included in the next version of the library.

**Closed** 2024-10-24 20:25 UTC
Labels: new feature, priority 1
