### ISSUE TITLE
Zooming can break charts when multiple ISeries[] are sharing an Axis 

### ISSUE THREAD

**Issue by jakobo06** [beto-rodriguez/LiveCharts2#1106] opened 2023-07-12 10:49 UTC
**Describe the bug**
When multiple ISeries[] series share an Axis and one of the ISeries[] is an empty ISeries array zooming out will break the chart, such that all the elements of the ISeries[] containing elements disappear. 

**To Reproduce**

View model code:
```c#
[ObservableObject]
public partial class ViewModel
{
    public ViewModel()
    {
        SeriesCollection1 = new ISeries[] {
            new CandlesticksSeries<FinancialPoint> {
                Values = new ObservableCollection<FinancialPoint>()
                {
                    new(new DateTime(2021, 1, 1), 523, 500, 450, 400),
                    new(new DateTime(2021, 1, 2), 500, 450, 425, 400)
                }
            }
        };
        SeriesCollection2 = new ISeries[] { };
        SharedXAxis = new Axis[] { new Axis() };
    }

    public ISeries[] SeriesCollection1 { get; set; }
    public ISeries[] SeriesCollection2 { get; set; }
    public Axis[] SharedXAxis { get; set; }
}
```
View code
```
<Grid>
    <Grid.RowDefinitions>
        <RowDefinition Height="*"/>
        <RowDefinition Height="*"/>
    </Grid.RowDefinitions>

    <lvc:CartesianChart
        Grid.Row="0"
        Series="{Binding SeriesCollection1}"
        XAxes="{Binding SharedXAxis}"
        ZoomMode="X">
    </lvc:CartesianChart>

    <lvc:CartesianChart
        Grid.Row="1"
        Series="{Binding SeriesCollection2}"
        XAxes="{Binding SharedXAxis}"
        ZoomMode="X">
    </lvc:CartesianChart>
</Grid>
```

When you zoom out the chart disappear

**Expected behavior**
I would expect it to behave the same as having only one ISeries[] with elements, i.e. disregard the empty ISeries[] collection and not break the chart.

**Screenshots**
I have attached a video of the chart breaking. I just scroll 
https://github.com/beto-rodriguez/LiveCharts2/assets/19285957/78798122-43c9-4012-b81e-320b7020d5e1

**Desktop (please complete the following information):**
    OS: Windows 11 22621.1848
    Browser: NA
    Version: v2.0.0-beta.810
    .NET Version: net6.0-windows

**Comment by beto-rodriguez** [comment] 2023-07-16 16:49
Thanks for the report, this issue is for sure related to #738, the problem is the same, the data has different length, and it causes the issue.

**Comment by beto-rodriguez** [comment] 2023-08-28 23:20
We can track this issue at #738, this should be fixed in the next release, thanks for the report.

**Closed by beto-rodriguez** 2023-08-28 23:20 UTC
Labels: bug, good first issue
