### ISSUE TITLE
Mouse events for arbitrary points on CartesianChart

### ISSUE THREAD

**Issue by mark-monteiro** [beto-rodriguez/LiveCharts2#423] opened 2022-03-16 21:38 UTC
**Is your feature request related to a problem? Please describe.**
CartesianChart already has mouse events for individual data points, but it would be nice to also have similar events for any position on the chart. The usefulness of these events is that they can provide event arguments with the point converted to the chart coordinate system.

For example, something like the `AddPointOnClick` example in the repository could be simplified by moving all the logic to the view model. Currently this example needs a separate implementation for each platform.

**Describe the solution you'd like**
I have a custom `CartesianChart` class I use in my own WPF project that adds these events. The same functionality could be added directly to the charts in the core library. I'm not too familiar with any of the platforms other that WPF, but I assume there would have to be a small platform-specific part to add handlers to the relevant mouse events for the platform and get the event coordinates.

The implementation is fairly simple. Basically the native events are forwarded directly with a custom event arguments object that also includes the chart-relative coordinates. The custom sub-class I am using is included below:

```cs
using System;
using System.Windows;
using System.Windows.Input;

using LiveCharts.Wpf;

namespace Foo;

/// <summary>
/// Extension of the <see cref="CartesianChart"/> component that adds mouse events that report their event position
/// as chart values using <see cref="Extentions.ConvertToChartValues(LiveCharts.Wpf.Charts.Base.Chart, Point, int, int)"/>.
/// </summary>
public class CustomCartesianChart : CartesianChart
{
    #region Dependency Properties

    /// <summary>
    /// Dependency property for <see cref="MouseDownPointCommand"/>.
    /// </summary>
    public static readonly DependencyProperty MouseDownPointCommandProperty =
        DependencyProperty.Register(nameof(MouseDownPointCommand), typeof(ICommand), typeof(CustomCartesianChart));

    /// <summary>
    /// Dependency property for <see cref="MouseUpPointCommand"/>.
    /// </summary>
    public static readonly DependencyProperty MouseUpPointCommandProperty =
        DependencyProperty.Register(nameof(MouseUpPointCommand), typeof(ICommand), typeof(CustomCartesianChart));

    /// <summary>
    /// Dependency property for <see cref="DoubleClickPointCommand"/>.
    /// </summary>
    public static readonly DependencyProperty DoubleClickPointCommandProperty =
        DependencyProperty.Register(nameof(DoubleClickPointCommand), typeof(ICommand), typeof(CustomCartesianChart));

    #endregion

    #region Events

    /// <summary>
    /// Event triggered when the <see cref="UIElement.MouseDown"/> event occurs on a point in the graph.
    /// </summary>
    public event EventHandler<MouseButtonPointEventArgs>? MouseDownPoint;

    /// <summary>
    /// Event triggered when the <see cref="UIElement.MouseUp"/> event occurs on a point in the graph.
    /// </summary>
    public event EventHandler<MouseButtonPointEventArgs>? MouseUpPoint;

    /// <summary>
    /// Event triggered when the <see cref="System.Windows.Controls.Control.MouseDoubleClick"/> event occurs on a point in the graph.
    /// </summary>
    public event EventHandler<MouseButtonPointEventArgs>? DoubleClickPoint;

    #endregion

    #region Command Properties

    /// <summary>
    /// Gets or sets a command to be executed after the <see cref="MouseDownPoint"/> event is triggered.
    /// </summary>
    public ICommand? MouseDownPointCommand {
        get => (ICommand?)GetValue(MouseDownPointCommandProperty);
        set => SetValue(MouseDownPointCommandProperty, value);
    }

    /// <summary>
    /// Gets or sets a command to be executed after the <see cref="MouseUpPoint"/> event is triggered.
    /// </summary>
    public ICommand? MouseUpPointCommand {
        get => (ICommand?)GetValue(MouseUpPointCommandProperty);
        set => SetValue(MouseUpPointCommandProperty, value);
    }

    /// <summary>
    /// Gets or sets a command to be executed after the <see cref="DoubleClickPoint"/> event is triggered.
    /// </summary>
    public ICommand? DoubleClickPointCommand {
        get => (ICommand?)GetValue(DoubleClickPointCommandProperty);
        set => SetValue(DoubleClickPointCommandProperty, value);
    }

    #endregion

    /// <summary>
    /// Initializes a new instance of the <see cref="CustomCartesianChart"/> class.
    /// </summary>
    public CustomCartesianChart()
        : base()
    {
        // Create mouse event handlers
        MouseDown += (sender, e) => HandleMouseEvent(sender, e, MouseDownPoint, MouseDownPointCommand);
        MouseUp += (sender, e) => HandleMouseEvent(sender, e, MouseUpPoint, MouseUpPointCommand);
        MouseDoubleClick += (sender, e) => HandleMouseEvent(sender, e, DoubleClickPoint, DoubleClickPointCommand);
    }

    /// <summary>
    /// Handle a mouse event by invoking the specified event handler and command. The arguments passed to the
    /// invoked methods includes the graph point that was clicked.
    /// </summary>
    private void HandleMouseEvent(object sender, MouseButtonEventArgs e, EventHandler<MouseButtonPointEventArgs>? eventHandler, ICommand? command)
    {
        // Do nothing if there is no handler or command listening to this event
        if (eventHandler == null && command == null) return;

        // Get the data point that was clicked
        // TODO: Make sure the point is within the graph?
        var point = this.ConvertToChartValues(e.GetPosition(this));

        // Invoke event handler, if any
        var pointArgs = new MouseButtonPointEventArgs(point, e);
        eventHandler?.Invoke(sender, pointArgs);

        // Invoke command, if possible
        if (command != null && command.CanExecute(pointArgs)) command.Execute(pointArgs);
    }
}

```

And this is the custom event argument class:

```cs
/// <summary>
/// Event arguments that describe a mouse event at a specific point in a LiveCharts chart.
/// </summary>
public class MouseButtonPointEventArgs : MouseButtonEventArgs
{
    /// <summary>
    /// Gets or sets the point on the chart associated with the event.
    /// </summary>
    public Point Point { get; set; }

    /// <summary>
    /// Initializes a new instance of the <see cref="MouseButtonPointEventArgs"/> class from an existing
    /// <see cref="MouseButtonEventArgs"/> instance.
    /// </summary>
    /// <param name="point">The point on the graph where the event occurred.</param>
    /// <param name="baseEvent">The arguments from the mouse event that occurred.</param>
    public MouseButtonPointEventArgs(Point point, MouseButtonEventArgs baseEvent)
        : this(point, (baseEvent ?? throw new ArgumentNullException(nameof(baseEvent))).MouseDevice, baseEvent.Timestamp, baseEvent.ChangedButton, baseEvent.StylusDevice)
    {
    }

    /// <summary>
    /// Initializes a new instance of the <see cref="MouseButtonPointEventArgs"/> class.
    /// </summary>
    /// <param name="point">The point on the graph where the event occurred.</param>
    /// <param name="mouse">The logical Mouse device associated with this event.</param>
    /// <param name="timestamp">The time when the input occurred.</param>
    /// <param name="button">The mouse button whose state is being described.</param>
    /// <param name="stylusDevice">The stylus device associated with this event.</param>
    public MouseButtonPointEventArgs(Point point, MouseDevice mouse, int timestamp, MouseButton button, StylusDevice stylusDevice)
        : base(mouse, timestamp, button, stylusDevice)
    {
        Point = point;
    }
}
```

**Describe alternatives you've considered**
The alternate solution above with a custom sub-class works well. I am just suggesting this to see if it seems like a good idea to add to the core library.

**Additional context**
The following events could also be potentially useful to add in a similar manner
- `MouseLeftButtonDown`
- `MouseLeftButtonUp`
- `MouseRightButtonDown`
- `MouseRightButtonUp`
- `MouseWheel`

**Comment by imms20** [comment] 2022-09-03 12:47
Hi @beto-rodriguez do you have any plans for providing support of such functionality? Actually one of my client is asking for such feature in the charts on the .net MAUI. At the moment we are looking into MAC and Windows Builds But later on can add android and ios. 

We need the Mouse cursor position functionality which gives us the cursor position on the chart. I have checked the documentation and samples but could not find anything useful.

**Comment by imms20** [comment] 2022-09-15 09:27
Hi @beto-rodriguez will it be possible to do it on winui and mac platform using maui? may be using handlers? Actually we want to release the our app and this is the only thing remaining on charting

**Comment by GF-Huang** [comment] 2022-09-23 19:40
Hello, is there any docs about handling data point click/select event? I can't find it even if I read: https://lvcharts.com/docs/WPF/2.0.0-beta.330/samples.lines.basic

**Comment by ricbrue** [comment] 2022-09-29 12:45
Hi, any news about this improvement?

**Comment by imms20** [comment] 2022-09-29 13:30
Hi @mark-monteiro i have seen your original post at the top. the problem is if the main chart does not give me any kind of command or event then in crossplatform or on handler level then what is the point of subclassing it.  Again i am asking about such feature on .net maui not on WPF

**Comment by beto-rodriguez** [comment] 2023-06-04 17:02
Since version beta-700, there are a couple of new functions that let us get the points or visuals at a given coordinate:

```
var points = chart.GetPointsAt(new LvcPoint((float)p.X, (float)p.Y));
var visuals = chart.GetVisualsAt(new LvcPoint((float)p.X, (float)p.Y));
```

I think that this is a good solution, because instead of re-inventing the wheel and create events for each supported platform, we can use the events the platform already provides, and just ask the chart for any point or visual at a given position, the web site and the repo have an example that shows this feature (AddPointOnClick sample).

As far as I can see this should be enough, any thoughts?

**Comment by mark-monteiro** [comment] 2023-06-05 14:45
This issue is not about adding any missing functionality to get the chart coordinates on mouse events; it is about adding these events/commands as a convenience to the `CartesianChart` class to simplify implementations in the view model.

If you look at the [AddPointOnClick](https://lvcharts.com/docs/WPF/2.0.0-beta.710/samples.events.addPointOnClick) example you mentioned (which I also mentioned in the original post), you'll notice that all the logic for the event handler has to be implemented in the view, rather than the view model. This is because the view model does not have any reference to the `CartesianChart` object in order to convert the point coordinates.

In my case (and I assume others), you want the handler logic to execute in the view model. Generally you would do this by binding to the equivalent command property for the event to a command in the view model (i.e. to handle the `MouseDown` event in the view model you would bind the `MouseDownCommand` property to a command in the view model). However, from inside the view model you don't generally have access to view objects like the `CartesianChart` (and usually also don't want to due to separation of concerns).

One way to get around this would be to add the event handler in the view, convert the point, then forward the event to a method in the view model. Another solution (which I provided above) would be to sub-class `CartesianChart` in order to add new commands that the view model can directly bind to which provide the converted point.

If the library natively added these events/commands to the `CartesianChart` object, then neither of those solutions would be necessary and the view model can bind directly to the new command, simplifying the implementation. If it is deemed too much of a maintenance burden to add the new events/commands that's also understandable. In that case the sub-classing solution works for me so feel free to close the issue.

**Comment by beto-rodriguez** [comment] 2023-07-15 04:39
That was a long and repetitive PR! but that should fix this issue, I updated the `Events/AddPointOnClick` and `General/Scrollable` samples to use commands instead, and yes, the same command is shared for all the supported platforms, this is definitely much cleaner.

This will be included in the next version of the library, the samples in the web site will be updated automatically with the changes in this PR, but we still missing a good article about events in the site.

**Closed** 2023-07-17 15:15 UTC
Labels: enhancement, priority 0
