### ISSUE TITLE
Click ChartPointPointerDown Application Crash

### ISSUE THREAD

**Issue by 285984303** [beto-rodriguez/LiveCharts2#989] opened 2023-04-26 10:03 UTC
private void cartesianChart1_ChartPointPointerDown(LiveChartsCore.Kernel.Sketches.IChartView chart, LiveChartsCore.Kernel.ChartPoint point)
        {
            FirstFloor.ModernUI.Windows.Controls.ModernDialog.ShowMessage( "You clicked " + point.PrimaryValue + ", " + point.SecondaryValue, "提示", MessageBoxButton.OK);

        }

**Comment by beto-rodriguez** [comment] 2023-06-08 20:59
Hi, I am not able to reproduce this issue, what is the error message you get? 

I will close this for now, please feel free to open a new issue with more information if the issue persists.

**Closed by beto-rodriguez** 2023-06-08 20:59 UTC
