### ISSUE TITLE
MAUI Closing App Throws NullReferenceException

### ISSUE THREAD

**Issue by DamianSuess** [beto-rodriguez/LiveCharts2#945] opened 2023-02-26 19:34 UTC
**Describe the bug**

When closing an application (i.e. UWP) using the Cartesian chart on **v2.0.0-beta.701** throws a **NullReferenceException** _Object reference not set to an instance of an object_.  I created a simple sample using static dummy data with only the CartesianChart on the page.

The call stack is provided below if this assists.

If there is any more info required, I'm happy to assist.

### Reproduce
Because animation can occur while either navigating away from the page or closing the app. This can be reproduced with either of the options below

* A) Resize the window and close it while it's animating
* B) Scroll the canvas with the use of `ZoomMode="X"` enabled

I attempted to fix the issue by wrapping the call in a try-catch, however, it still gets thrown.

```cs
    private async void RunDrawingLoop()
    {
        if (_isDrawingLoopRunning) return;
        _isDrawingLoopRunning = true;

        var ts = TimeSpan.FromSeconds(1 / MaxFps);
        while (!CanvasCore.IsValid)
        {
            try
            {
                skiaElement?.InvalidateSurface();
                await Task.Delay(ts);
            }
            catch
            {
                break;
            }
        }

        _isDrawingLoopRunning = false;
    }
```

### Sample XAML

```xml
    <lvc:CartesianChart Series="{Binding Series}"
                        YAxes="{Binding YAxes}"
                        LegendPosition="Bottom"
                        LegendBackgroundPaint="{Binding LegendTextPaint}"
                        LegendTextPaint="{Binding LegendTextPaint}"
                        LegendTextSize="16"
                        ZoomMode="X">
    </lvc:CartesianChart>
```

**Expected behavior**
The system should know that the view is no longer available and not attempt to perform actions (_see screenshot_).

**Screenshots**

MontionCanvas.cs and Call Stack
![image](https://user-images.githubusercontent.com/1216684/220238519-7efb6a9d-5879-4d58-8154-7fe689703d6c.png)

**Desktop (please complete the following information):**
- .NET MAUI
- Windows 10.0.19044.2604

**Additional context**

Related to:
* #660
* SkiaSharp, https://github.com/mono/SkiaSharp/issues/1880  If this is the case, the system should act before the SkiaSharp method gets called.

**Comment by daltzctr** [comment] 2023-05-11 20:30
Doing `chart.CoreCanvas.Dispose()` before application shut down works for me.

**Comment by DamianSuess** [comment] 2023-05-12 19:13
interesting @daltzctr. Are you performing this in the view's `.xaml.cs` or in the ViewModel during navigation away?

**Comment by daltzctr** [comment] 2023-05-12 19:45
In the `.xaml.cs` during `OnDisappearing`. I try not to leak UI elements into the VM in anyway.

**Comment by DamianSuess** [comment] 2023-05-12 20:04
thank you

**Comment by beto-rodriguez** [comment] 2023-06-07 23:58
Probably related to #934

Since Maui uses also WindowsAppSDK, and the issue is present in that platform, I need to verify if the fix applied in #934 would also work for  MAUI (probably yes).

**Comment by DamianSuess** [comment] 2023-06-08 22:48
If it does resolve this as well, that would be awesome!
Since we use this control in a `ContentView` surprisingly it's not as straightforward as using Maui's `ContentPage` `OnDisappearing()` method.

**Comment by beto-rodriguez** [comment] 2023-07-15 23:48
This is now fixed with the referenced commit and will be included in the next version of the library. thanks for the report.

**Closed** 2023-07-16 18:35 UTC
Labels: bug, maui
