### ISSUE TITLE
Vanishing tick marks and offset.

### ISSUE THREAD

**Issue by Varmod** [beto-rodriguez/LiveCharts2#1128] opened 2023-07-20 08:02 UTC
**Describe the bug**
X axis tick marks are offset by default.
Also when I turn on the Y axis tick marks the X ones completely vanish.

**To Reproduce**

`SolidColorPaint ticksColor = new SolidColorPaint(SKColors.Gray, 1);

			XAxes = new Axis[]
			{
				new Axis
				{
					Name = "foo",
					NamePaint = new SolidColorPaint(SKColors.Black),
					TextSize = 12,
					MinLimit = _minLimitX,
					MaxLimit = _maxLimitX,
					SeparatorsPaint = null, 
					Padding = new Padding(10),
					NamePadding = new Padding(10),
					TicksPaint = ticksColor,
					SubticksPaint = ticksColor,
					DrawTicksPath = true
				}
			};

			YAxes = new Axis[]
			{
				new Axis
				{
					Name = "bar",
					NamePaint = new SolidColorPaint(SKColors.Black),
					TextSize = 12,
					MinLimit = _minLimitY1,
					MaxLimit = _maxLimitY1,
					SeparatorsPaint = null,
					//TicksPaint = ticksColor,
					//SubticksPaint = ticksColor,
					//DrawTicksPath = true
				},
				new Axis
				{
					Name = "baz",
					NamePaint = new SolidColorPaint(SKColors.Black),
					TextSize = 12,
					Position = LiveChartsCore.Measure.AxisPosition.End,
					SeparatorsPaint = null,
					MinLimit = _minLimitY2,
					MaxLimit = _maxLimitY2,
					//TicksPaint = ticksColor,
					//SubticksPaint = ticksColor,
					//DrawTicksPath = true
				}
			};`

**Expected behavior**
No offset and visible ticks.

**Screenshots**
Y ticks disabled.
![Screenshot 2023-07-20 095526](https://github.com/beto-rodriguez/LiveCharts2/assets/52281562/f4f0171c-52a2-4ec9-b278-863f266bab93)
Y ticks enabled.
![Screenshot 2023-07-20 095602](https://github.com/beto-rodriguez/LiveCharts2/assets/52281562/6e3b3674-2b10-4c6d-a68a-807e4b7dabc8)

**Desktop (please complete the following information):**
 - Windows - Avalonia app

**Comment by beto-rodriguez** [comment] 2024-10-16 20:25
This is already fixed with [7610a07](https://github.com/beto-rodriguez/LiveCharts2/commit/7610a07f1591e30843bbe90e0a2058c933311063), it will be included in the next version of the library.

I will close this issue as duplicate of #1587, but again this is already fixed and a new version with the fix will be at NuGet soon.

**Closed by beto-rodriguez** 2024-10-16 20:25 UTC
Labels: visual glitch, priority 1
