### ISSUE TITLE
Blazor: XAxis is moved below margin frame when more than 1 YAxes are used

### ISSUE THREAD

**Issue by MeetMichal** [beto-rodriguez/LiveCharts2#1356] opened 2023-11-13 22:52 UTC
**Describe the bug**
Having two Y axes, my X axe is moved sligthly below chart margin frame

**To Reproduce**
1. Add one X DateTimeAxis
2. Add two Y axes
3. Add two LineSeries<DateTimePoint>, one using first Y axe and the other using second Y axe
4. X axe is moved below margin frame

**Expected behavior**
Ticks and labels in X axe are closer to the chart, like for Y axes

**Additional contex**
It happens only when one Y axis has Position set to End. When both Y axes have Position set to Start then X axis is shown fine

**Screenshots**
![image](https://github.com/beto-rodriguez/LiveCharts2/assets/150547065/e368f28e-5dfe-4f0f-af35-742c816492e6)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: chrome
 - Version rc1.2

**Comment by LabuzzMichal** [comment] 2023-11-17 19:30
Hi @beto-rodriguez (or @btordz ?). Did you have some time to take a look ? :)

**Comment by MeetMichal** [comment] 2023-11-17 19:38
@beto-rodriguez Did you find some time to take a look ? :) Let me know if more info is needed

**Comment by MeetMichal** [comment] 2023-12-04 20:14
Hi @beto-rodriguez , kindly reminder :)

**Comment by alextim** [comment] 2024-04-22 21:42
I have the same problem but with Avalonia11

**Comment by beto-rodriguez** [comment] 2024-10-22 20:01
Hello and thanks for the report.

I am closing this as duplicate of #1587.

The good news is that this issue is already fixed in the dev branch and will be included in the next version of the library!

**Closed by beto-rodriguez** 2024-10-22 20:01 UTC
Labels: visual glitch, priority 0
