### ISSUE TITLE
Chart not showing in .net 8 preview

### ISSUE THREAD

**Issue by cgp1976** [beto-rodriguez/LiveCharts2#1215] opened 2023-09-05 09:17 UTC
Hi, 

I have just downloaded the sample project and changed the targetframework to net8.0-windows10.0.19041.0 and I am ble to compile and run successfully just that the chart not showing. only the grid line appears.

Sample Project
https://github.com/beto-rodriguez/MauiApp-LiveCharts

**Comment by DJVova** [comment] 2023-09-07 16:56
I wrote about this problem, and admin told me to wait for the final version net8 in November. But something tells me that nothing will change....And we need to report this problem to the developers of net8.

**Comment by beto-rodriguez** [comment] 2023-09-07 17:05
I have hopes that this is an issue on MAUI/SkiaSharp and they can fix it in the final release but let me try to reproduce and find where the issue is (MAUI, SkiaSharp or LiveCharts).

**Comment by beto-rodriguez** [comment] 2023-09-08 19:08
I was able to reproduce this on net8, it seems that there is a bug in the `Binding`, if you set the series from code behind it works!

instead of:

```
<lvc:CartesianChart Series="{Binding Series}" LegendPosition="Right"></lvc:CartesianChart>
```

set the series using c#

```
[XamlCompilation(XamlCompilationOptions.Compile)]
public partial class View : ContentPage
{
    public View()
    {
        InitializeComponent();

        var vm = new ViewModelsSamples.Design.LinearGradients.ViewModel();
        chart.Series = vm.Series;
    }
}

<lvc:CartesianChart x:Name="chart" LegendPosition="Right"></lvc:CartesianChart>
```

This does not seem like an issue in  LiveCharts, but I will keep an eye on this.

**Comment by HobDev** [comment] 2023-10-06 11:43
I am developing a windows app on .NET 8 RC1. The pie chart was not visible on Windows. But when I set WidthRequest and HeightRequest to the Chart it become visible.

**Comment by Kuurama** [comment] 2024-02-29 03:33
The charts are still not showing in preview (avalonia 11) (latest dotnet 8 release)

**Comment by beto-rodriguez** [comment] 2024-09-16 18:49
Hello

I am not able to reproduce this issue on any platform.

There are multiple reasons unrelated with this library that could cause a chart to be hidden, here are some common issues:

- https://github.com/beto-rodriguez/LiveCharts2/issues/1483
- https://github.com/beto-rodriguez/LiveCharts2/issues/1581

Please make sure you are not facing a similar issue to the list above.

I will close this for now, but feel free to create a new issue if this persists.

**Closed by beto-rodriguez** 2024-09-16 18:49 UTC
Labels: maui, requires external features, preview-feature
