### ISSUE TITLE
Want to ask why my post and my tag are not on it

### ISSUE THREAD

**Issue by 2099521591** [beto-rodriguez/LiveCharts2#1629] opened 2024-10-08 05:51 UTC
Want to ask why my post and my tag are not on it

Here is my viewmodel code

    XAxes = new Axis[] { new DateTimeAxis(TimeSpan.FromHours(1), date => date.ToString("dd HH")) };

    Series = new ObservableCollection<ISeries>
{
    new ColumnSeries<DateTimePoint>
    {

        Values = new ObservableCollection<DateTimePoint>
    {
        new DateTimePoint(new DateTime(2021, 1, 1,11,12,13), 3),
        new DateTimePoint(new DateTime(2021, 1, 1,12,13,13), 6),
        new DateTimePoint(new DateTime(2021, 1, 1,13,14,13), 5),
        new DateTimePoint(new DateTime(2021, 1, 1,14,15,13), 3),
        new DateTimePoint(new DateTime(2021, 1, 1,15,12,13), 5),
        new DateTimePoint(new DateTime(2021, 1, 1,16,12,13), 8),
        new DateTimePoint(new DateTime(2021, 1, 1,17,12,13), 6),
          new DateTimePoint(new DateTime(2021, 1, 1,18,12,13), 10),
          new DateTimePoint(new DateTime(2021, 1, 1,19,12,13), 12),
          new DateTimePoint(new DateTime(2021, 1, 1,20,12,13), 11),
            new DateTimePoint(new DateTime(2021,1,1,21,12,13), 15),
            new DateTimePoint(new DateTime(2021,1,1,22,12,13), 19),

    }
    }
};

The state manifested
![image](https://github.com/user-attachments/assets/2d48e3b9-b432-416b-97e2-b3fb21d622a2)

**Comment by beto-rodriguez** [comment] 2024-10-11 01:39
Hello

it seems that your axis is not binded to your control, please take a look at the docs:

https://livecharts.dev/docs/Maui/2.0.0-rc2/samples.axes.dateTimeScaled

Specially at:

`YAxes="{Binding YAxes}"`

I will close this for now since this seems like a question, feel free to reply or create discussion if you require more help.

**Comment by 2099521591** [comment] 2024-10-11 07:10
I'm glad you can answer my question, I copied the code according to the documentation and my xaml code is as follows

  <lvc:CartesianChart
      Grid.Row="2"
      Series="{Binding Series}"
      XAxes="{Binding XAxes}" />
Using the example of the linked document you provided, I found that when I changed the formatter format in DateTimeAxis to date => date.toString ("dd HH"),
this would happen, I couldn't find a solution can you help me, thanks

**Comment by beto-rodriguez** [comment] 2024-10-26 16:59
The issue is that you also have minutes and seconds in your `DateTime`, LiveCharts scales the `DateTime.Ticks` property.

Changing:

`new DateTimePoint(new DateTime(2021, 1, 1, 11, 12, 13), 3)` 
to 
`new DateTimePoint(new DateTime(2021, 1, 1, 11, 0, 0), 3)` will make the trick.

Ill close this for now, but feel free to reply/create a new issue if this is not fixed.

**Closed by beto-rodriguez** 2024-10-26 16:59 UTC
