### ISSUE TITLE
Title not visible when creating an in-memory cartesian chart

### ISSUE THREAD

**Issue by raffaeler** [beto-rodriguez/LiveCharts2#1340] opened 2023-11-03 12:10 UTC
**Describe the bug**
I am generating a chart in a Console application using `SKCartesianChart` with a `ScatterSeries`. The chart appears as expected but the `Title` does not show up.

**To Reproduce**
1. Use the sample code: https://github.com/beto-rodriguez/LiveCharts2/blob/b0e32c2c8997dae8f0c5d740cfdd39748018e685/samples/ConsoleSample/ConsoleSample/Program.cs#L20
2. limit the sample to the first part, until the image is saved on disk and remove everything else

**Expected behavior**
I expect to see the Title in the generated image

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by beto-rodriguez** [comment] 2023-11-05 23:41
Duplicate of #1285, that bug is already fixed and will be included in version rc2, for now you can downgrade to beta.950.

**Closed by beto-rodriguez** 2023-11-05 23:41 UTC
