### ISSUE TITLE
The LiveChartsCore.SkiaSharpView.Uno.WinUi assemblies should have the LiveChartsCore.SkiaSharpView.WinUI

### ISSUE THREAD

**Issue by igiona** [beto-rodriguez/LiveCharts2#938] opened 2023-02-17 14:42 UTC
The LiveChartsCore.SkiaSharpView.Uno.WinUI Version 2.0.0-beta.701 assemblies have different namespaces compared to the LiveChartsCore.SkiaSharpView.WinUI Version 2.0.0-beta.701 assmeblies.

This cause issues while compiling cross-platform libraries which need to reference the one or the other package depending on the target (e.g. WASM or Windows).

**Expected behavior**
The .Uno* assemblies should have the same namespace as their respective non-Uno DLLs.

**Additional context**
Building a Uno app for WASM and Windows might require to load the packages which target different frameworks.

**Comment by igiona** [comment] 2023-03-09 18:48
> Here's a workaround:
> 
> As most of the types cannot be inherited from, the only possible solution is to use conditional exclusions for Uno (starting from Uno 4.8):
> 
> ```
> <Page x:Class="App1.MainPage"
>       xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
>       xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
>       xmlns:local="using:App1"
>       xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
>       xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
> 
>       xmlns:unolvc="http://uno.ui#using:LiveChartsCore.SkiaSharpView.Uno.WinUI"
>       xmlns:winlvc="using:LiveChartsCore.SkiaSharpView.WinUI"
>       mc:Ignorable="d unolvc"
> 
>       Background="{ThemeResource ApplicationPageBackgroundThemeBrush}">
> 
>     <Grid>
>         <unolvc:CartesianChart Height="400"
>                                Grid.Column="0"
>                                Grid.Row="0"
>                                Series="{Binding BackTofLeftSeries}"
>                                TooltipPosition="Hidden"
>                                AnimationsSpeed="00:00:00.000" />
>         <winlvc:CartesianChart Height="400"
>                                Grid.Column="0"
>                                Grid.Row="0"
>                                Series="{Binding BackTofLeftSeries}"
>                                TooltipPosition="Hidden"
>                                AnimationsSpeed="00:00:00.000" />
>     </Grid>
> </Page>
> ```
> 
> and the following exclusion in the corresponding csproj file:
> 
> ```
> <ItemGroup>
>    <ExcludeXamlNamespaces Include="winlvc" />
> </ItemGroup>
> ```

With Windows WInUi as target it does work:
![image](https://user-images.githubusercontent.com/1524038/224124829-6e164442-5f05-4df4-84ce-93274bdacc60.png)

But the workaround doesn't work with WASM.
The code compiles, but the chart is not displayed.
![image](https://user-images.githubusercontent.com/1524038/224125135-66584c22-094b-4433-9d8d-bd9343849fa5.png)

**Comment by jeromelaban** [comment] 2023-03-09 18:50
@igiona you may also need to include this
```
   <IncludeXamlNamespaces Include="unolvc" />
```

I've updated the post above.

**Comment by igiona** [comment] 2023-03-10 05:24
> ```
>    <IncludeXamlNamespaces Include="unolvc" />
> ```

Indeed this helped, thanks!

**Comment by beto-rodriguez** [comment] 2023-03-17 05:25
I will take a look into this next week, and let you know, sorry about the late response.

**Comment by francoistanguay** [comment] 2023-03-17 13:37
No worries, as usual, happy to have the team help and answer questions as needed

**Comment by jeromelaban** [comment] 2023-04-27 21:36
Thanks for the update! The error you're getting is generally caused by an outdated/misaligned version of SkiaSharp. Which version are you building with?

**Comment by beto-rodriguez** [comment] 2023-04-27 21:42
oh, I see there is a new version of SkiaSharp, I am on [2.88.2](https://www.nuget.org/packages/SkiaSharp/2.88.2) will try to upgrade to fix that.

**Comment by jeromelaban** [comment] 2023-04-28 12:29
> The package `LiveChartsCore.SkiaSharpView.Uno.WinUi` is for Uno.WinUI (also for the Uno.Windows project).
> Then `LiveChartsCore.SkiaSharpView.WinUI` is for WinUI.

Regarding this, both packages are installed in the same project conditionally (particularly in libraries, which are now present by default in Uno projects) and are generally expected to be be useable from source, particularly in XAML from either Uno and WinUI Target Frameworks. In general, when code is shared between WinAppSDK and Uno, it's best to use the same namespaces (`LiveChartsCore.SkiaSharpView.WinUI` in this case).

**Comment by beto-rodriguez** [comment] 2023-04-30 03:34
> The error you're getting is generally caused by an outdated/misaligned version of SkiaSharp

@jeromelaban thanks! It works now! WindowsSDK, Wasm and Gtk are working, but on android it seems that the app is not starting:

![image](https://user-images.githubusercontent.com/10853349/235334143-6ea5cd18-9e95-4360-a91d-dd82344ccd40.png)

That log is repeating over an over (already waited about 10 mins with no luck).

am I missing something? I am trying this at #994, I am not completely sure if I am missing something or this is an issue.

**Comment by jeromelaban** [comment] 2023-05-01 13:06
@beto-rodriguez Thanks for the update. This is quite curious. If you break on all exceptions, do you see anything showing up?

**Comment by beto-rodriguez** [comment] 2023-05-01 13:22
These are some exceptions I see in the log:

```
[EGL_emulation] eglCreateContext: 0x7ce45d16cbd0: maj 2 min 0 rcv 2
[EGL_emulation] eglMakeCurrent: 0x7ce45d16cbd0: ver 2 0 (tinfo 0x7ce66c76f180) (first time)
[monodroid-assembly] open_from_bundles: failed to load assembly Microsoft.Extensions.Configuration.Abstractions.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Microsoft.Extensions.Hosting.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Microsoft.Extensions.FileProviders.Physical.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Microsoft.Extensions.FileProviders.Abstractions.dll
[OpenGLRenderer] Davey! duration=848ms; Flags=1, FrameTimelineVsyncId=173824, IntendedVsync=40301309888467, Vsync=40301759888449, InputEventId=0, HandleInputStart=40301765645025, AnimationStart=40301765670225, PerformTraversalsStart=40301765890425, DrawStart=40302079668825, FrameDeadline=40301326555133, FrameInterval=40301765597525, FrameStartTime=16666666, SyncQueued=40302125514025, SyncStart=40302128609425, IssueDrawCommandsStart=40302129637425, SwapBuffers=40302153359725, FrameCompleted=40302161634825, DequeueBufferDuration=43400, QueueBufferDuration=627600, GpuCompleted=40302161424825, SwapBuffersCompleted=40302161634825, DisplayPresentTime=25769803779, 
Loaded assembly: /data/data/com.companyname.UnoPlatformSample/files/.__override__/Microsoft.Extensions.Configuration.Abstractions.dll [External]
Loaded assembly: /data/data/com.companyname.UnoPlatformSample/files/.__override__/Microsoft.Extensions.Hosting.dll [External]
Loaded assembly: /data/data/com.companyname.UnoPlatformSample/files/.__override__/Microsoft.Extensions.FileProviders.Physical.dll [External]
Loaded assembly: /data/data/com.companyname.UnoPlatformSample/files/.__override__/Microsoft.Extensions.FileProviders.Abstractions.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly Microsoft.Extensions.DependencyInjection.dll
Loaded assembly: /data/data/com.companyname.UnoPlatformSample/files/.__override__/Microsoft.Extensions.DependencyInjection.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly Uno.Extensions.Hosting.dll
Loaded assembly: /data/data/com.companyname.UnoPlatformSample/files/.__override__/Uno.Extensions.Hosting.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly Uno.Extensions.Storage.dll
Loaded assembly: /data/data/com.companyname.UnoPlatformSample/files/.__override__/Uno.Extensions.Storage.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly Uno.Extensions.Serialization.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Uno.Extensions.Http.dll
Loaded assembly: /data/data/com.companyname.UnoPlatformSample/files/.__override__/Uno.Extensions.Serialization.dll [External]
Loaded assembly: /data/data/com.companyname.UnoPlatformSample/files/.__override__/Uno.Extensions.Http.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly Uno.Extensions.Localization.dll
Loaded assembly: /data/data/com.companyname.UnoPlatformSample/files/.__override__/Uno.Extensions.Localization.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly Microsoft.Extensions.Configuration.dll
Loaded assembly: /data/data/com.companyname.UnoPlatformSample/files/.__override__/Microsoft.Extensions.Configuration.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly Microsoft.Extensions.Configuration.EnvironmentVariables.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Microsoft.Extensions.Configuration.CommandLine.dll
Loaded assembly: /data/data/com.companyname.UnoPlatformSample/files/.__override__/Microsoft.Extensions.Configuration.EnvironmentVariables.dll [External]
Loaded assembly: /data/data/com.companyname.UnoPlatformSample/files/.__override__/Microsoft.Extensions.Configuration.CommandLine.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly Microsoft.Extensions.Primitives.dll
Loaded assembly: /data/data/com.companyname.UnoPlatformSample/files/.__override__/Microsoft.Extensions.Primitives.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly Microsoft.Extensions.Configuration.FileExtensions.dll
Loaded assembly: /data/data/com.companyname.UnoPlatformSample/files/.__override__/Microsoft.Extensions.Configuration.FileExtensions.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly Microsoft.Extensions.Configuration.Json.dll
Loaded assembly: /data/data/com.companyname.UnoPlatformSample/files/.__override__/Microsoft.Extensions.Configuration.Json.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly System.Text.Json.dll
Loaded assembly: /data/data/com.companyname.UnoPlatformSample/files/.__override__/System.Text.Json.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly Microsoft.Extensions.Options.dll
Loaded assembly: /data/data/com.companyname.UnoPlatformSample/files/.__override__/Microsoft.Extensions.Options.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly Microsoft.Extensions.Logging.Configuration.dll
Loaded assembly: /data/data/com.companyname.UnoPlatformSample/files/.__override__/Microsoft.Extensions.Logging.Configuration.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly Microsoft.Extensions.Options.ConfigurationExtensions.dll
Loaded assembly: /data/data/com.companyname.UnoPlatformSample/files/.__override__/Microsoft.Extensions.Options.ConfigurationExtensions.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly Microsoft.Extensions.Configuration.Binder.dll
Loaded assembly: /data/data/com.companyname.UnoPlatformSample/files/.__override__/Microsoft.Extensions.Configuration.Binder.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly Uno.Extensions.Toolkit.dll
Loaded assembly: /data/data/com.companyname.UnoPlatformSample/files/.__override__/Uno.Extensions.Toolkit.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly Microsoft.Extensions.Logging.Console.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Microsoft.Extensions.Logging.Debug.dll
Loaded assembly: /data/data/com.companyname.UnoPlatformSample/files/.__override__/Microsoft.Extensions.Logging.Console.dll [External]
Loaded assembly: /data/data/com.companyname.UnoPlatformSample/files/.__override__/Microsoft.Extensions.Logging.Debug.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly Microsoft.Extensions.Localization.Abstractions.dll
Loaded assembly: /data/data/com.companyname.UnoPlatformSample/files/.__override__/Microsoft.Extensions.Localization.Abstractions.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly System.Text.Encodings.Web.dll
Loaded assembly: /data/data/com.companyname.UnoPlatformSample/files/.__override__/System.Text.Encodings.Web.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly Uno.Extensions.Serialization.Refit.dll
[monodroid-assembly] open_from_bundles: failed to load assembly UnoPlatformSample.DataContracts.dll
Loaded assembly: /data/data/com.companyname.UnoPlatformSample/files/.__override__/Uno.Extensions.Serialization.Refit.dll [External]
Loaded assembly: /data/data/com.companyname.UnoPlatformSample/files/.__override__/UnoPlatformSample.DataContracts.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Refit.dll
Loaded assembly: /data/data/com.companyname.UnoPlatformSample/files/.__override__/Refit.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly System.Runtime.Intrinsics.dll
Loaded assembly: /data/data/com.companyname.UnoPlatformSample/files/.__override__/System.Runtime.Intrinsics.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly Microsoft.Extensions.Http.dll
Loaded assembly: /data/data/com.companyname.UnoPlatformSample/files/.__override__/Microsoft.Extensions.Http.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly Uno.Extensions.Http.Refit.dll
Loaded assembly: /data/data/com.companyname.UnoPlatformSample/files/.__override__/Uno.Extensions.Http.Refit.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly Refit.HttpClientFactory.dll
Loaded assembly: /data/data/com.companyname.UnoPlatformSample/files/.__override__/Refit.HttpClientFactory.dll [External]
[monodroid-assembly] Shared library 'kernel32.dll' not loaded, p/invoke 'GetStdHandle' may fail
Thread started: Console logger queue processing thread #10
[monodroid-assembly] open_from_bundles: failed to load assembly Uno.UI.Adapter.Microsoft.Extensions.Logging.dll
Loaded assembly: /data/data/com.companyname.UnoPlatformSample/files/.__override__/Uno.UI.Adapter.Microsoft.Extensions.Logging.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly Uno.Core.Extensions.Collections.dll
Loaded assembly: /data/data/com.companyname.UnoPlatformSample/files/.__override__/Uno.Core.Extensions.Collections.dll [External]
[Choreographer] Skipped 75 frames!  The application may be doing too much work on its main thread.
[OpenGLRenderer] Davey! duration=1299ms; Flags=0, FrameTimelineVsyncId=173832, IntendedVsync=40301776555115, Vsync=40303026555065, InputEventId=0, HandleInputStart=40303031436025, AnimationStart=40303031462125, PerformTraversalsStart=40303050610825, DrawStart=40303074151425, FrameDeadline=40301809888447, FrameInterval=40303031193125, FrameStartTime=16666666, SyncQueued=40303074516925, SyncStart=40303074732825, IssueDrawCommandsStart=40303074832125, SwapBuffers=40303075156325, FrameCompleted=40303076532925, DequeueBufferDuration=24800, QueueBufferDuration=830500, GpuCompleted=40303076423825, SwapBuffersCompleted=40303076532925, DisplayPresentTime=549755813888, 
[0:] Uno.Extensions.Navigation.Navigators.ContentControlNavigator: Information: NavigateAsync - Starting Navigation - Navigator: ContentControlNavigator Request: 
[monodroid-assembly] Shared library 'liblog' not loaded, p/invoke '__android_log_print' may fail
[DOTNET] [40m[32minfo[39m[22m[49m: Uno.Extensions.Navigation.Navigators.ContentControlNavigator[0]
[DOTNET]       NavigateAsync - Starting Navigation - Navigator: ContentControlNavigator Request: 
[0:] Uno.Extensions.Navigation.Navigators.ContentControlNavigator: Warning: Show - Missing view for navigation path ''
[DOTNET] [40m[1m[33mwarn[39m[22m[49m: Uno.Extensions.Navigation.Navigators.ContentControlNavigator[0]
[DOTNET]       Show - Missing view for navigation path ''
[0:] Uno.Extensions.Navigation.Navigators.ContentControlNavigator: Information: CreateControlFromType - Creating control of type FrameView
[DOTNET] [40m[32minfo[39m[22m[49m: Uno.Extensions.Navigation.Navigators.ContentControlNavigator[0]
[DOTNET]       CreateControlFromType - Creating control of type FrameView
[EGL_emulation] app_time_stats: avg=335.73ms min=2.07ms max=863.12ms count=3
[0:] Uno.Extensions.Navigation.Navigators.FrameNavigator: Information: NavigateAsync - Starting Navigation - Navigator: FrameNavigator Request: Main
[DOTNET] [40m[32minfo[39m[22m[49m: Uno.Extensions.Navigation.Navigators.FrameNavigator[0]
[DOTNET]       NavigateAsync - Starting Navigation - Navigator: FrameNavigator Request: Main
[monodroid-assembly] open_from_bundles: failed to load assembly ViewModelsSamples.dll
Loaded assembly: /data/data/com.companyname.UnoPlatformSample/files/.__override__/ViewModelsSamples.dll
[CompatibilityChangeReporter] Compat change id reported: 171228096; UID 10153; state: ENABLED
[monodroid-assembly] open_from_bundles: failed to load assembly es/System.Private.CoreLib.resources.dll
[monodroid-assembly] open_from_bundles: failed to load assembly es/System.Private.CoreLib.resources.dll
[EGL_emulation] app_time_stats: avg=40.55ms min=4.76ms max=243.88ms count=25
[EGL_emulation] app_time_stats: avg=33.91ms min=32.29ms max=35.94ms count=30
```

**Comment by beto-rodriguez** [comment] 2023-05-01 13:26
Full output:

[output.txt](https://github.com/beto-rodriguez/LiveCharts2/files/11365542/output.txt)

**Comment by jeromelaban** [comment] 2023-05-01 14:42
Got it, but does the debugger break on first chance exceptions? @nickrandolph may also know more about this as your sample uses navigation extensions.

**Comment by beto-rodriguez** [comment] 2023-05-01 16:32
Thanks @nickrandolph!  that helped me to find the issue!

It seems that on android the `FrameworkElement.FindName()` is not finding the canvas, while on the rest of the platforms is. Is there something else I can try there?

The issue happens [here](https://github.com/beto-rodriguez/LiveCharts2/blob/update-uno/src/skiasharp/LiveChartsCore.SkiaSharpView.Uno.WinUI/MotionCanvas.xaml.cs#L58) because `_skiaElement` is `null` on android.

**Comment by beto-rodriguez** [comment] 2023-05-02 05:35
Thanks for the help, it seems that the error is on my side, I should be able to get that working, again thanks for the assistance.

**Comment by beto-rodriguez** [comment] 2023-05-02 07:05
After some research it seems that the SkiaSharp view is not loaded on android (I think all the mobile project).

I followed your example [here](https://github.com/unoplatform/Uno.Samples/tree/master/UI/SkiaSharpTest/SkiaSharpTest) with no luck, notice I am using a newer template of Uno.

I created [this](https://github.com/beto-rodriguez/UnoApp) repository without livecharts that illustrates the issue I am facing. 

The highlights in that repo is that I am adding a reference SkiaSharp, but as illustrated on your example, on WindowsSDK I referenced `SkiaSharp.Views.WinUI` and on the rest of the platforms `SkiaSharp.Views.Uno.WinUI`.

Also in this sample I am not using the `FindName` method and just using using the name in the code I set via `x:Name`, but it seems that on mobile the view is not loaded (doing this at Presentation/MainPage):

![image](https://user-images.githubusercontent.com/10853349/235601499-86cc4cbd-1421-481a-82e5-68445ea74084.png)

**Comment by jeromelaban** [comment] 2023-05-02 12:55
[The `skia` namespace is special in Uno's XAML](https://platform.uno/docs/articles/platform-specific-xaml.html), in and in the context of a standard app, it gets removed from the visual tree. Yet, that feature is not yet compatible with class libraries until .NET 8 (until the `net8.0-browser` TFM is introduced).

In the meantime, try using a different namespace name.

**Comment by beto-rodriguez** [comment] 2023-05-02 14:23
@jeromelaban Thanks for pointing that out! that totally fixed it! sorry and thanks for all your help!

**Comment by beto-rodriguez** [comment] 2023-05-02 14:49
I will close this issue for now since namespaces are aligned now in the latest NuGet package, and the docs in the website are updated.

Thanks to all the Uno team for your help!

**Closed by beto-rodriguez** 2023-05-02 14:49 UTC

**Comment by igiona** [comment] 2023-05-08 18:28
I confirm it works, many thanks!
