### ISSUE TITLE
Axis not re-drawn.

### ISSUE THREAD

**Issue by alexachso** [beto-rodriguez/LiveCharts2#1402] opened 2023-12-13 20:18 UTC
**Describe the bug**
With an empty ObservableCollection<ObservablePoint> for a series, when we assign float.NaN value to UnitWidth property of the XAxis, the XAxis disappears from the screen, which might be understandable. But then, if we re-assign a valid value to the UnitWidth property, for example, the value 2.0f, the XAxis is not re-drawn. Then, if we add points to the empty collection, the points will appear on the chart but the XAxis is still missing. This gives the feeling that the graph is broken and we need to restart the application.

If the collection for the series is not empty when we assign float.NaN value to UnitWidth property of the XAxis, the XAxis disappears from the screen. But then, if we re-assign a valid value to the UnitWidth property, for example, the value 2.0f, the XAxis is re-drawn, which is the expected behavior.

**Expected behavior**
The XAxis should re-appear as normal after we assign a valid value to its UnitWidth.

**Additional context**
WPF application.

**Workaround**
I check if the value is valid before I assign it to the UnitWidth. 😄

**Comment by beto-rodriguez** [comment] 2024-09-15 19:01
Hello

I am afraid that there is not an easy for for this, you must handle your `NaN` value, for example use `1` or any other value that matches your needs.

The problem is that LibveCharts tracks the the current position of the shapes in the UI (to create the animations), so when you forced the `NaN`, then the tracked object becomes NaN, and there is no way to return that to a number again.

I don't really understand the reason to set the UnitWidth to `NaN`, maybe you can tell me what you are trying to do, and I can help you to fix the problem following another path.

I will close this for now, but feel free to reply or create a new thread explaining what you were trying to do.

**Closed by beto-rodriguez** 2024-09-15 19:01 UTC
Labels: not a bug
