### ISSUE TITLE
SkCartesianChart Leaves Ghost image

### ISSUE THREAD

**Issue by mcash95** [beto-rodriguez/LiveCharts2#1333] opened 2023-10-26 14:55 UTC
**Describe the bug**
When i build a SkCartesianchart and then save as .png, the series remains in my UI control as a ghost image.

UI Control image

![image](https://github.com/beto-rodriguez/LiveCharts2/assets/58281418/06fae0ff-e0ed-4138-956b-71e1997bf276)

backend code (for saving only)
![image](https://github.com/beto-rodriguez/LiveCharts2/assets/58281418/2e30b10d-8b01-49bb-a7bd-968790e82f9d)

**Comment by beto-rodriguez** [comment] 2023-10-27 18:10
Hello

This seems strange, I am not able to reproduce this issue, it seems to work properly in this repo.

Can you please provide a minimal reproducible example where I can get the issue?

**Comment by mcash95** [comment] 2023-10-30 20:16
Page:

`<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="THSDashBoardMobile.Pages.AdminGraphPage"
             xmlns:toolkit="http://schemas.microsoft.com/dotnet/2022/maui/toolkit"
             xmlns:models="clr-namespace:THSDashBoardMobile.Models" 
             xmlns:lvc="clr-namespace:LiveChartsCore.SkiaSharpView.Maui;assembly=LiveChartsCore.SkiaSharpView.Maui"
             xmlns:viewmodels="clr-namespace:THSDashBoardMobile.Models.ViewModels" x:DataType="viewmodels:AdminGraphViewModel"
             Title="Admin Graph">
    <Grid ColumnDefinitions="0.25*,*">
    <ListView ItemsSource="{Binding Company.Regions}" Grid.Column="0" WidthRequest="200">
            <FlyoutBase.ContextFlyout>
                <MenuFlyout>
                    <MenuFlyoutItem Text="Add All Regions" Clicked="Add_all_Regions"/>
                </MenuFlyout>
            </FlyoutBase.ContextFlyout>
        <ListView.ItemTemplate>
            <DataTemplate x:DataType="{x:Type models:Region}">
                <ViewCell AutomationId="{Binding Supervisor}">
                    <toolkit:Expander >
                        <toolkit:Expander.GestureRecognizers>
                            <DragGestureRecognizer CanDrag="True" DragStarting="DragGestureRecognizer_DragStarting" DropCompleted="DragGestureRecognizer_DropCompleted"/>
                        </toolkit:Expander.GestureRecognizers>
                            <FlyoutBase.ContextFlyout>
                                
                                <MenuFlyout>
                                    <MenuFlyoutItem Text="Add All Stores" Clicked="Add_all_Stores"/>
                                    
                                </MenuFlyout>
                                
                            </FlyoutBase.ContextFlyout>
                            <toolkit:Expander.Header>
                            <Frame BorderColor="{StaticResource THSGreen}" Margin="10" BackgroundColor="Transparent" MaximumWidthRequest="300" MinimumWidthRequest="150"  HorizontalOptions="StartAndExpand">
                                <Label Text="{Binding Supervisor}" TextColor="{AppThemeBinding Light={StaticResource DarkTextColor},Dark={StaticResource LightTextColor}}" FontSize="Body"/>
                            </Frame>
                        </toolkit:Expander.Header>
                        <toolkit:Expander.Content >
                                <ListView x:DataType="{x:Type models:Region}" ItemsSource="{Binding Stores}" Grid.Column="0" MaximumHeightRequest="300">
                                    <ListView.ItemTemplate>
                                        <DataTemplate>
                                            <ViewCell x:DataType="{x:Type models:Region}">
                                                <VerticalStackLayout x:DataType="{x:Type models:Store}">
                                                    <VerticalStackLayout.GestureRecognizers>
                                                        <DragGestureRecognizer CanDrag="True" DragStarting="DragGestureRecognizer_DragStarting" DropCompleted="DragGestureRecognizer_DropCompleted"/>
                                                    </VerticalStackLayout.GestureRecognizers>
                                                    <Label Text="{Binding SiteID}" FontSize="20" FontAttributes="Bold" Margin="20,0,0,0"/>
                                                    <HorizontalStackLayout x:DataType="{x:Type models:Store}">
                                                        <Label Text="{Binding Manager,StringFormat='Manager : {0}'}" FontSize="12" FontAttributes="Italic,Bold" Margin="20,0,10,0" HorizontalTextAlignment="Start"/>
                                                    </HorizontalStackLayout>
                                                </VerticalStackLayout>
                                            </ViewCell>
                                        </DataTemplate>
                                    </ListView.ItemTemplate>
                                </ListView>
                        </toolkit:Expander.Content>
                    </toolkit:Expander>
                </ViewCell>
                
            </DataTemplate>
        </ListView.ItemTemplate>
    </ListView>
        <lvc:CartesianChart Grid.Column="1" TooltipFindingStrategy="CompareOnlyX" x:Name="graph1" LegendPosition="Left" Series="{Binding Series}" ZoomMode="Both">
            <lvc:CartesianChart.GestureRecognizers>
                <DropGestureRecognizer AllowDrop="True" Drop="DropGestureRecognizer_Drop"/>
            </lvc:CartesianChart.GestureRecognizers>
            <FlyoutBase.ContextFlyout>
                <MenuFlyout>

                    <MenuFlyoutSubItem Text="Mode">

                        <MenuFlyoutItem Text="Sales By Hour" Clicked="Sales_Hour_Mode"/>

                        <MenuFlyoutItem Text="Mark Report" Clicked="Mark_Mode"/>

                    </MenuFlyoutSubItem>

                    <MenuFlyoutItem Text="Save Chart" Clicked="Save_Graph"/>

                    <MenuFlyoutItem Text="Clear Graph" Clicked="Clear_graph"/>

                </MenuFlyout>
            </FlyoutBase.ContextFlyout>
        </lvc:CartesianChart>
    </Grid>
</ContentPage>`

ViewModel:

`using CommunityToolkit.Mvvm.ComponentModel;
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using LiveChartsCore.SkiaSharpView;
using LiveChartsCore;


namespace THSDashBoardMobile.Models.ViewModels
{
    public partial class AdminGraphViewModel:ObservableObject
    {
        [ObservableProperty]
        public ObservableCollection<Region> regions = new();

        [ObservableProperty]
        public Company company;

        /* 
         * Graphing properties
         * these are only active on Desktop versions.
         */
        #region

        [ObservableProperty]
        public int mode=1;

        [ObservableProperty]
        public ObservableCollection<Store> graphStores = new();

        [ObservableProperty]
        public ObservableCollection<Models.Region> graphRegions = new();

        [ObservableProperty]
        public ObservableCollection<ISeries> series = new();

        #endregion
    }
}
`

Backend:
`using LiveChartsCore.Measure;
using LiveChartsCore.SkiaSharpView;
using LiveChartsCore.SkiaSharpView.Painting;
using LiveChartsCore.SkiaSharpView.SKCharts;
using SkiaSharp;
using System.Diagnostics;
using THSDashBoardMobile.Models;
using THSDashBoardMobile.Models.ViewModels;


namespace THSDashBoardMobile.Pages;
 
public partial class AdminGraphPage : ContentPage
{
    AdminGraphViewModel view;

	public AdminGraphPage(AdminGraphViewModel vm,DashboardDB dashboard,Company company)
    {
		InitializeComponent();
		BindingContext=vm;
        view = vm;
		vm.Company=company;
	}
    protected override void OnNavigatingFrom(NavigatingFromEventArgs args)
    {
        base.OnNavigatingFrom(args);
        Clear_graph(this, null);
    }
    private void DropGestureRecognizer_Drop(object sender, DropEventArgs e)
    {
        try
        {
            switch (view.Mode)
            {
                case 1:
                    if (e.Data.Properties["Location"] is Store)
                    {
                        Store obj = (Store)e.Data.Properties["Location"];
                        view.GraphStores.Add(obj);
                        SalesHourModeApplied();
                    }
                    else
                    {
                        Models.Region obj = (Models.Region)e.Data.Properties["Location"];
                        view.GraphRegions.Add(obj);
                        SalesHourModeApplied();
                    }
                    break;
                case 2:
                    if (e.Data.Properties["Location"] is Store)
                    {
                        Store obj = (Store)e.Data.Properties["Location"];
                        view.GraphStores.Add(obj);
                        MarkModeApplied();
                    }
                    else
                    {
                        Models.Region obj = (Models.Region)e.Data.Properties["Location"];
                        view.GraphRegions.Add(obj);
                        MarkModeApplied();
                    }
                    break;
            }

        }
        catch (KeyNotFoundException k)
        {
            Debug.Write(k.Message);
        }
    }
    private void DragGestureRecognizer_DragStarting(object sender, DragStartingEventArgs e)
    {
        
        if((sender as Element).BindingContext is Store)
        {
            Store obj = (sender as Element).BindingContext as Store;
            e.Data.Properties.Add("Location", obj);
        }
        else
        {
            Models.Region obj = (sender as Element).BindingContext as Models.Region;
            e.Data.Properties.Add("Location", obj);
        }
    }
    private void DragGestureRecognizer_DropCompleted(object sender, DropCompletedEventArgs e)
    {
        if((sender as Element).BindingContext is Store)
        {
            Store store = (sender as Element).BindingContext as Store;
            if (view.GraphStores.Contains(store))
            {
                ((sender as Element).Parent.Parent.Parent.BindingContext as Models.Region).Stores.Remove(store);
            }
        }
        else
        {
            Models.Region region = (sender as Element).BindingContext as Models.Region;
            if(view.GraphRegions.Contains(region))
            {
                view.Company.Regions.Remove(region);
            }
        }
    }
    private void Clear_graph(object sender, EventArgs e)
    {
        foreach (Models.Region region in view.GraphRegions)
        {
            (this.BindingContext as AdminGraphViewModel).Company.Regions.Add(region);
        }
        foreach (Store s in view.GraphStores)
        {
            Models.Region region = view.Company.Regions.Where(r => r.Supervisor == s.Manager).FirstOrDefault();
            try
            {
                region.Stores.Insert(region.Stores.IndexOf(region.Stores.Where(i => Convert.ToInt32(s.SiteID) < Convert.ToInt32(i.SiteID)).First()), s);
            }
            catch (InvalidOperationException i)
            {
                region.Stores.Add(s);
                Debug.Write(i.Message);
            }
        }
        view.GraphStores.Clear();
        view.GraphRegions.Clear();
        view.Series.Clear();
    }
    private void Add_all_Stores(object sender, EventArgs e)
    {
        if(((sender as Element).BindingContext as Models.Region).Stores.Count > 0)
        {
            foreach (Store s in ((sender as Element).BindingContext as Models.Region).Stores)
            {
                view.GraphStores.Add(s);
            }
            switch (view.Mode)
            {
                case 1:
                    SalesHourModeApplied();
                    break;
                case 2:
                    MarkModeApplied();
                    break;
            }
            foreach(Store s in view.GraphStores)
            {
                ((sender as Element).BindingContext as Models.Region).Stores.Remove(s);
            }
        }
    }
    private void Mark_Mode(object sender, EventArgs e)
    {
        view.Mode = 2;
        view.Series.Clear();
        MarkModeApplied();
    }
    private void Save_Graph(object sender, EventArgs e)
    {
        var skChart = new SKCartesianChart() { Width = 1200, Height=900, Series=view.Series,XAxes=graph1.XAxes,YAxes=graph1.YAxes,Background=SKColors.Black,LegendPosition=LegendPosition.Left,LegendTextPaint=new SolidColorPaint(color:SKColors.White) };
        skChart.SaveImage("C:/Users/Max/Desktop/Chart.png");
    }
    private void Sales_Hour_Mode(object sender, EventArgs e)
    {
        view.Mode = 1;
        view.Series.Clear();
        SalesHourModeApplied();
    }
    private void MarkModeApplied()
    {
        graph1.XAxes = new Axis[]
        {
                new Axis
                {
                    Labels = new string[] {"Multiples %", "$300 %","3IPT %", "$500 %"},
                    LabelsRotation=45,
                }
        };
        graph1.YAxes = new Axis[]
        {
                new Axis
                {
                    Labeler=label=>label.ToString("P0"),
                    MinLimit=0,
                }
        };
        view.Series.Clear();
        if (view.GraphStores.Count > 0 || view.GraphRegions.Count > 0)
        {
            foreach (Store s in view.GraphStores)
            {
                view.Series.Add(new ColumnSeries<double>
                {
                    Name = s.SiteID.ToString(),
                    Values = new double[] { s.MarkReport.Multi, s.MarkReport.ThreeHundR, s.MarkReport.ThreeIPTR, s.MarkReport.FiveHundR },
                    YToolTipLabelFormatter = point => $"{point.Coordinate.PrimaryValue:P1}",
                    DataLabelsFormatter = point => $"{s.SiteID} : {point.Coordinate.PrimaryValue:P1}",
                    DataLabelsPosition = DataLabelsPosition.Middle,
                    DataLabelsPaint = new SolidColorPaint(SKColors.White),
                    DataLabelsSize = 16,
                    DataLabelsRotation = -90,
                    DataPadding=new LiveChartsCore.Drawing.LvcPoint(0.5, 0),
                });
            }
            foreach (Models.Region r in view.GraphRegions)
            {
                view.Series.Add(new ColumnSeries<double>
                {
                    Name = r.Supervisor,
                    Values = new double[] { r.MarkReport.Multi, r.MarkReport.ThreeHundR, r.MarkReport.ThreeHundR, r.MarkReport.FiveHundR },
                    YToolTipLabelFormatter = point => $"{point.Coordinate.PrimaryValue:P1}",
                    DataLabelsFormatter = point => $"{r.Supervisor} : {point.Coordinate.PrimaryValue:P1}",
                    DataLabelsPosition = DataLabelsPosition.Middle,
                    DataLabelsPaint = new SolidColorPaint(SKColors.White),
                    DataLabelsSize = 16,
                    DataLabelsRotation = -90,
                    DataPadding = new LiveChartsCore.Drawing.LvcPoint(0.5, 0),

                });
            }
        }
    }
    private void SalesHourModeApplied()
    {
        view.Series.Clear();
        graph1.XAxes = new Axis[]
        {
            new Axis{LabelsRotation=30}
        };
        graph1.YAxes = new Axis[]
        {
            new Axis{LabelsRotation=-30}
        };
        if (view.GraphRegions.Count > 0 || view.GraphStores.Count > 0)
        {
            foreach (Store s in view.GraphStores)
            {
                view.Series.Add(s.SalesByHr.FirstOrDefault());
            }
            foreach (Models.Region r in view.GraphRegions)
            {
                view.Series.Add(r.SalesByHr.FirstOrDefault());
            }
        }
    }
    private void Add_all_Regions(object sender, EventArgs e)
    {
        if (view.Company.Regions.Count > 0)
        {
            foreach(Models.Region r in view.Company.Regions)
            {
                view.GraphRegions.Add(r);
            }
            switch(view.Mode)
            {
                case 1:
                    SalesHourModeApplied();
                    break;
                case 2:
                    MarkModeApplied();
                    break;
            }   
            foreach(Models.Region r in view.GraphRegions)
            {
                view.Company.Regions.Remove(r);
            }
        }
    }
}`

**Comment by mcash95** [comment] 2023-10-30 20:52
The cause is when you use references to the LiveCharts Cartesianchart while building the SKCartesianChart.

ex
 `        var skChart = new SKCartesianChart() { Width = 1200, Height=900, Series=new ISeries[] {new LineSeries<int> { Values = new int[]{ 1,2,3,1,2,3} } },XAxes=graph1.XAxes,YAxes=graph1.YAxes,
            Background=SKColors.Black,LegendPosition=LegendPosition.Left,LegendTextPaint=new SolidColorPaint(color:SKColors.White) };
`
This will leave ghost axis because of the graph1.Xaxes chunk, but will not leave a ghost series image because the series is built in the call.

`        var skChart = new SKCartesianChart() { Width = 1200, Height=900, Series=view.Series,XAxes=graph1.XAxes,YAxes=graph1.YAxes,
            Background=SKColors.Black,LegendPosition=LegendPosition.Left,LegendTextPaint=new SolidColorPaint(color:SKColors.White) };
`

this will leave ghost axis and a ghost image due to the graph1 chunks. 


Hopefully that helps some, i was able to verify that within my own code with LineSeries and ColumnSeries

**Comment by Arasfon** [comment] 2024-06-30 20:22
I can confirm this is an issue. Passing series and/or axes by reference results in ghost images. Recreating new series and axes helped.

**Comment by beto-rodriguez** [comment] 2024-10-21 18:07
Fixed with the referenced commit and will be included in the next version of the library, thanks for the report.

**Closed** 2024-10-24 20:25 UTC
Labels: more info required
